### ISSUE TITLE
html-webpack-plugin doesn't include options when generating the index.html

### ISSUE THREAD

**Issue by dmcclureagl** [preboot/angular2-webpack#102]
Inside webpack.config.js under:

`      
new HtmlWebpackPlugin({
        template: './src/public/index.html',
        chunksSortMode: 'dependency',
        base: '/'
     })
`

Specifying "base" should interact with the html at compilation see https://github.com/ampedandwired/html-webpack-plugin under configuration, should be easily specified into the template as "<%= htmlWebpackPlugin.options.base %>".

**Comment by Foxandxss** [comment]
I am not sure if I follow.

**Comment by dmcclureagl** [comment]
Solved via another method, but in short the template compilation from the config was interfering with the generation of additional HTML tags within the starters index.html.
