### ISSUE TITLE
Enable Cors

### ISSUE THREAD

**Issue by rennen** [preboot/angular2-webpack#103]
Guys,

Great work! Very easy to setup and start working.
However, I didn't quite understand how to add CORS support when running locally. Can you please help?

**Comment by rennen** [comment]
The webpack.config.js has a

...
devServer: {
   headers: { "Access-Control-Allow-Origin": "*" }
}
...

**Comment by ollwenjones** [comment]
@rennen Depending on your final deployment goals, you can always use the [webpack-dev-server proxy](https://webpack.github.io/docs/webpack-dev-server.html#proxy), rather than having to worry about CORS.
