### ISSUE TITLE
Import Bootstrap SCSS in vendor.ts

### ISSUE THREAD

**Issue by hijoncon** [preboot/angular2-webpack#113]
How to import bootstrap scss in vendor.ts? I added this in my vendor.ts `import 'bootstrap-sass/assets/stylesheets/_bootstrap.scss';` and I am getting a error message below.

ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader!./~/raw-loader!./~/postcss-loader!./~/sass-loader!./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss
Module build failed: 
/*!
             ^
      Invalid CSS after "module.exports": expected "{", was '= "@charset \\"UTF-8'
      in /Users/x203949/Sites/angular2-webpack/node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss (line 1, column 15)
 @ ./~/bootstrap-sass/assets/stylesheets/_bootstrap.scss 4:14-250
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 302 bytes

**Comment by chaseoli** [comment]
+1

**Comment by hijoncon** [comment]
I'm closing this top now.  I think the best way is to put that in your `src/style/app.scss`

`$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';`

**Comment by CSharpFan** [comment]
```// Bootstrap variables
$navbar-border-radius: 15px;

// Support for bootstrap itself
@import "../../node_modules/bootstrap/scss/bootstrap.scss";
``` This is currently in my `app.scss`. If there's a better way to avoid the `../..`, please shout :)

**Comment by deeg** [comment]
Does this not work for you?

`@import '~bootstrap/scss/bootstrap';`

**Comment by CSharpFan** [comment]
No, it does not, OS = Win. Anything I can test?

**Comment by leonlr** [comment]
I change this line 
{test: /\.(scss|sass)$/, exclude: root('src', 'style'), loader: 'raw-loader!postcss-loader!sass-loader'}
to 
{test: /\.(scss|sass)$/, include: root('src', 'app'), loader: 'raw-loader!postcss-loader!sass-loader'},
and it's work for me.
