### ISSUE TITLE
RC 4 Platform Browser - ELEMENT_PROBE_PROVIDERS

### ISSUE THREAD

**Issue by hijoncon** [preboot/angular2-webpack#116]
Looks like we have deprecated 
ELEMENT_PROBE_PROVIDERS coming from
`import { ELEMENT_PROBE_PROVIDERS } from '@angular/platform-browser';`

My app still working after removing that in my app. Not sure if that is the right thing to do.
Any suggestion?

Thanks!

**Comment by Foxandxss** [comment]
Yes, I have it on my list of things to kill. Will do. Thanks.

**Comment by hijoncon** [comment]
@Foxandxss thank you
