### ISSUE TITLE
Import component convention

### ISSUE THREAD

**Issue by Menencia** [preboot/angular2-webpack#119]
In `app.routes.ts`, you wrote : 

`import { HomeComponent } from './home'`

Is there a convention that tells Angular to look for `./home/home.component.ts` ?

My editor doesn't recognize the syntax and throws me a `Cannot resolve symbol` error. (PHPStorm 10.0.2)

**Comment by Foxandxss** [comment]
Yes, that is called a `barrel` (you can check angular style guide) and for that concrete import we have [this barrel](https://github.com/preboot/angular2-webpack/blob/master/src/app/home/index.ts)
