### ISSUE TITLE
Production version

### ISSUE THREAD

**Issue by rajegit** [preboot/angular2-webpack#120]
Hi 
Thanks for this code, I have a question how to make code ready for production ?

Rajeit

**Comment by Foxandxss** [comment]
`npm run build` and that will create a dist folder with your production code.

**Comment by rajegit** [comment]
Thanks I tried the exact code , for my-app ( absolutely no modification) . When I did `npm run build` this is what I get in index.html
Html Webpack Plugin:

  Error: Child compilation failed:
  Entry module not found: Error: Cannot resolve 'file' or 'directory' ~/myproject/src/index.html in ~/myproject:
  Error: Cannot resolve 'file' or 'directory'~/myproject/src/index.html in ~/myproject
  
  - compiler.js:76 
    [webpack_boilerplate]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:214 Compiler.
    [webpack_boilerplate]/[webpack]/lib/Compiler.js:214:10
  
  - Compiler.js:403 
    [webpack_boilerplate]/[webpack]/lib/Compiler.js:403:12
  
  - Tapable.js:67 Compiler.next
    [webpack_boilerplate]/[tapable]/lib/Tapable.js:67:11
  
  - CachePlugin.js:40 Compiler.
    [webpack_boilerplate]/[webpack]/lib/CachePlugin.js:40:4
  
  - Tapable.js:71 Compiler.applyPluginsAsync
    [webpack_boilerplate]/[tapable]/lib/Tapable.js:71:13
  
  - Compiler.js:400 Compiler.
    [webpack_boilerplate]/[webpack]/lib/Compiler.js:400:9
  
  - Compilation.js:577 Compilation.
    [webpack_boilerplate]/[webpack]/lib/Compilation.js:577:13
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [webpack_boilerplate]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:572 Compilation.
    [webpack_boilerplate]/[webpack]/lib/Compilation.js:572:10
  
  - Tapable.js:67 Compilation.next
    [webpack_boilerplate]/[tapable]/lib/Tapable.js:67:11
  
  - UglifyJsPlugin.js:140 Compilation.
    [webpack_boilerplate]/[webpack]/lib/optimize/UglifyJsPlugin.js:140:4
  
  - Tapable.js:71 Compilation.applyPluginsAsync
    [webpack_boilerplate]/[tapable]/lib/Tapable.js:71:13
  
  - Compilation.js:567 Compilation.
    [webpack_boilerplate]/[webpack]/lib/Compilation.js:567:9
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [webpack_boilerplate]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:563 Compilation.
    [webpack_boilerplate]/[webpack]/lib/Compilation.js:563:8
  
  - Tapable.js:60 Compilation.applyPluginsAsync
    [webpack_boilerplate]/[tapable]/lib/Tapable.js:60:69
  
  - Compilation.js:525 Compilation.seal
    [webpack_boilerplate]/[webpack]/lib/Compilation.js:525:7
  
  - Compiler.js:397 Compiler.
    [webpack_boilerplate]/[webpack]/lib/Compiler.js:397:15
  
  - Tapable.js:103 
    [webpack_boilerplate]/[tapable]/lib/Tapable.js:103:11
  
  - Compilation.js:445 Compilation.
    [webpack_boilerplate]/[webpack]/lib/Compilation.js:445:10
  
  - Compilation.js:344 Compilation.errorAndCallback
    [webpack_boilerplate]/[webpack]/lib/Compilation.js:344:3
  
  - Compilation.js:358 Compilation.
    [webpack_boilerplate]/[webpack]/lib/Compilation.js:358:11
  
  - NormalModuleFactory.js:29 onDoneResolving
    [webpack_boilerplate]/[webpack]/lib/NormalModuleFactory.js:29:20
  
  - NormalModuleFactory.js:85 
    [webpack_boilerplate]/[webpack]/lib/NormalModuleFactory.js:85:20
  
  - async.js:726 
    [webpack_boilerplate]/[async]/lib/async.js:726:13
  
  - async.js:52 
    [webpack_boilerplate]/[async]/lib/async.js:52:16
  
  - async.js:241 done
    [webpack_boilerplate]/[async]/lib/async.js:241:17
  
  - async.js:44 
    [webpack_boilerplate]/[async]/lib/async.js:44:16
  
  - async.js:723 
    [webpack_boilerplate]/[async]/lib/async.js:723:17

**Comment by Foxandxss** [comment]
You changed the config of html-webpack-plugin but didn't move the index. Just read the error :)

**Comment by rajegit** [comment]
thanx @Foxandxss I fig that out :) and corrected it . Now eveything is blank , just says Loading .... when I open index.html

**Comment by Foxandxss** [comment]
You need a server to serve the page. Try `lite-server` or `http-server`

```
$ npm install -g lite-server
$ lite-server
```

That inside the dist folder.
