### ISSUE TITLE
Webpack configuration isn't watching template files

### ISSUE THREAD

**Issue by snolflake** [preboot/angular2-webpack#123]
Whenever I modify a template I need to restart the development server with `npm run server` to get the changes bundled. It seems to be something related to the `webpack-dev-server` itself and/or the html loader, but all workarounds that I've found involves some dirty configuration tricks. 

Since the main purpose of this repo is to provide a proper webpack configuration for angular 2 I'd hope to get some insight in how to solve this and confirm that it is indeed an issue within the configuration provided in this repo.

Thanks for any help! :sweat_smile:

**Comment by Foxandxss** [comment]
html-loader is not being used on the templates. Also I don't see that problem in my machine :/

**Comment by snolflake** [comment]
@Foxandxss oh I see, they use the raw loader, so the issues that I've found in the internets have nothing todo with what I'm experiencing.

I'll dig a little deeper then...

**Comment by snolflake** [comment]
Just for the record, actually it seems to watch **only ts files** just after I get a couple of builds to fail (due to ts error or whatever) while watching, so I'ts definitely something else which I'd rather to live with than debug myself.

Thanks for the prompt reply anyway, much appreciated!
