### ISSUE TITLE
rc5 update

### ISSUE THREAD

**Issue by PunkDog** [preboot/angular2-webpack#133]
I've been enjoying your build for a long time now, but the newest update from Angular Team (RC5) is giving me nightmares. Will you update the repo to rc5, or can you give me few hints on how to structure my app using ngModule?

Thanks.

**Comment by Foxandxss** [comment]
Right, sorry. I'm part of the angular team, and I was exhausted.

Will update today, promise.

**Comment by 31H0B1eV** [comment]
@PunkDog hi, you can check this pull request [Rc.5](https://github.com/preboot/angular2-webpack/pull/134)
