### ISSUE TITLE
Children components are not rendered after build

### ISSUE THREAD

**Issue by Chyngyz** [preboot/angular2-webpack#135]
After building the project, children components are not rendered, while on dev-server everything is fine.
Ways to implement the issue:
* Bare install the repo,
* Create any component, use Input decorator for passing data to the component
* Use newly created component in the template of any other components
* Define the component in `app.module.ts` in `declarations` property
* Run build `npm run build`

When serving from `dist`, the defined component is not rendered. 

My project got big, and when I build it says:

```
Template parse errors:
Can't bind to 'isfixed' since it isn't a known property of 'rkrt-header'.
```

even if I already defined the components in my `app.module.ts`, while on dev-server everything is fine.

I even tried declaring it in `directives` property within the component, but same error. 

Please help to solve the issue

**Comment by Foxandxss** [comment]
It is a known bug with RC5 to be fixed on RC6 (which is due for early this week).

You can see more here https://github.com/angular/angular/issues/10618

**Comment by Chyngyz** [comment]
@Foxandxss Thanks for the quick reply, will wait for RC6 impatiently.
