### ISSUE TITLE
add webpack-dashboard

### ISSUE THREAD

**Issue by phra** [preboot/angular2-webpack#138]
hi,

i've found this [repository](https://github.com/FormidableLabs/webpack-dashboard).

it would be nice to include in our starter kits.

what do you think guys?

@Foxandxss

**Comment by Foxandxss** [comment]
It is pretty, I give you that.

**Comment by phra** [comment]
sure!

i'll work on it in spare time and send a PR if everything is going well!

**Comment by phra** [comment]
@Foxandxss 

done! try it and let me know what you think about it!

cheers. :beers:

**Comment by phra** [comment]
sorry, i've forgotten to manage other envs than dev.
now it's fixed.

**Comment by kartsims** [comment]
Tested in dev and reviewed the code, seems good to me.
