### ISSUE TITLE
.html loader breaks HtmlWebpackPlugin templating

### ISSUE THREAD

**Issue by mattdistefano** [preboot/angular2-webpack#141]
I think this is what #102 was getting at - according to the [docs on HtmlWebpackPlugin  templating](https://github.com/ampedandwired/html-webpack-plugin/blob/master/docs/template-option.md), the `{test: /\.html$/, loader: 'raw'}` loader config ends up running `src\public\index.html` through the raw loader rather than the ejs loader that HtmlWebpackPlugin would otherwise use, effectively disabling templating. Seems like throwing a `exclude: root('src', 'public')` into the loader config fixes things, or you might be able to specify the default ejs loader explicitly as part of the template filename you pass into the `HtmlWebpackPlugin` constructor opts.

**Comment by Foxandxss** [comment]
Can you give me a concrete example in how is that breaking up? But yes, HtmlWebpackPlugin works a weird way with that.

**Comment by mattdistefano** [comment]
So if you change your template to include some ejs template expressions (the plugin seems to support other template languages but ejs is apparently the default), you'll see the built index.html doesn't include the interpolated value. From what I gather, this is because, behind the scenes, the plugin is plumbing the index.html through webpack loaders, and is picking up the raw loader from the config vs. the ejs loader it would default to.

So, src\public\index.html:
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= htmlWebpackPlugin.options.title %></title>
    <link rel="icon" type="image/x-icon" href="/img/favicon.ico">

    <base href="/">
  </head>
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>
```

Renders:
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= htmlWebpackPlugin.options.title %></title>
    <link rel="icon" type="image/x-icon" href="/img/favicon.ico">

    <base href="/">
  </head>
  <body>
    <my-app>Loading...</my-app>
  <script type="text/javascript" src="http://localhost:8080/js/polyfills.js"></script><script type="text/javascript" src="http://localhost:8080/js/vendor.js"></script><script type="text/javascript" src="http://localhost:8080/js/app.js"></script></body>
</html>
```

But if you change the loader to: `{test: /\.html$/, loader: 'raw', exclude: root('src', 'public')}`, you get:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Webpack App</title>
    <link rel="icon" type="image/x-icon" href="/img/favicon.ico">

    <base href="/">
  </head>
  <body>
    <my-app>Loading...</my-app>
  <script type="text/javascript" src="http://localhost:8080/js/polyfills.js"></script><script type="text/javascript" src="http://localhost:8080/js/vendor.js"></script><script type="text/javascript" src="http://localhost:8080/js/app.js"></script></body>
</html>
```

("Webpack App" seems to be the default value of `htmlWebpackPlugin.options.title`.)

Arguably, I guess maybe this isn't broken per se - maybe users should have to opt-in to the templating features of the plugin. But it has the feel of something that's broken, so maybe at minimum a note in the config file would be useful?

**Comment by Foxandxss** [comment]
Is the most sensible solution.

Thanks.
