### ISSUE TITLE
Prod build

### ISSUE THREAD

**Issue by jbeckton** [preboot/angular2-webpack#142]
Hello.

I was wondering how I could create a production build on my local machine. I guess I could change the webpack.config variable isProd to true but I was hoping for a way to produce a production build without hacking the config. Adding a task for production builds would be great.

Our CI setup does not support node.js yet so we have to generate builds locally and deploy the static files.

**Comment by Foxandxss** [comment]
`$ npm run build`

And copy the files from `/dist/`.

I am going to update the readme.
