### ISSUE TITLE
Errors with SASS

### ISSUE THREAD

**Issue by steveblue** [preboot/angular2-webpack#143]
I am trying to port a project from angular-cli to this starter. I have .scss at the component level that will not compile.

For instance:

src/app/view/login
    - login.component.ts
    - login.component.scss

I tried using `require` in `login.component.ts` like so:

`styles: [require('./login.component.scss')]`

But I get an error : 

```
client?cd17:47./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader!./~/raw-loader!./~/postcss-loader!./~/sass-loader!./src/app/view/login/login.component.scss
Module build failed: 
:host{
             ^
      Invalid CSS after "module.exports": expected "{", was '= ":host {\\n  width'
      in /Users/steve/www/angular2-webpack/src/app/view/login/login.component.scss (line 1, column 15)
Error: 
:host{
             ^
      Invalid CSS after "module.exports": expected "{", was '= ":host {\\n  width'
      in /Users/steve/www/angular2-webpack/src/app/view/login/login.component.scss (line 1, column 15)
    at options.error (/Users/steve/www/angular2-webpack/node_modules/node-sass/lib/index.js:272:32)
 @ ./src/app/view/login/login.component.scss 4:14-351

```
It seems like PostCSS loader is failing on all SCSS files attached to components. When I change the following line in webpack.config.ts the Errors go away:

FROM: 
```
     // all css required in src/app files will be merged in js files
      {test: /\.scss$/, exclude: root('src', 'style'), loader: 'raw!postcss!sass'},
```

TO:
```
      // all css required in src/app files will be merged in js files
      {test: /\.scss$/, exclude: root('src', 'style'), loader: 'raw!sass'},
```

This is more of a support request. Is there a gitter channel for this repo? If not, please make one.

**Comment by Foxandxss** [comment]
Honestly, all the SCSS part was in here when I came to maintain the repo and I never touched it again. I will play with scss a bit to see if I can repro it and fix it.

>Is there a gitter channel for this repo? If not, please make one.
There is not, and I hate Gitter with all my heart. Is the slowest and most horrible platform ever made.

**Comment by steveblue** [comment]
@Foxandxss The UI is a bit clunky, but at the very least everyone using this repo can have a forum to get help from others!

**Comment by steveblue** [comment]
I got my web app to finally build :) but none of the components are styled :(

**Comment by Foxandxss** [comment]
I created the gitter.

**Comment by steveblue** [comment]
OK, this issue was propagated by some instances of styles property on @Component were not Arrays but just require statement. But now I have a separate issue, the global .scss in src/style is not getting bundled with the entire app.

**Comment by steveblue** [comment]
TY @Foxandxss !

**Comment by steveblue** [comment]
OK, Verified the problem with global SASS exists with the use of import statements.

My app.scss looks like this:

```
// Authored Dependencies
@import "util/variables";
@import "util/colors";
@import "util/fonts";
@import "util/mixins";
@import "util/sprites";

// Application Styles
@import "base";
```

And In the console after the build I see these errors:

```
VM79633:84 Error: Uncaught (in promise): TypeError: Cannot read property 'import' of undefined
    at resolvePromise (eval at 623 (polyfills.js:790), <anonymous>:558:32)
    at eval (eval at 623 (polyfills.js:790), <anonymous>:535:14)
    at ZoneDelegate.invoke (eval at 623 (polyfills.js:790), <anonymous>:332:29)
    at Object.onInvoke (eval at <anonymous> (vendor.js:602), <anonymous>:53:41)
    at ZoneDelegate.invoke (eval at 623 (polyfills.js:790), <anonymous>:331:35)
    at Zone.run (eval at 623 (polyfills.js:790), <anonymous>:225:44)
    at eval (eval at 623 (polyfills.js:790), <anonymous>:591:58)
    at ZoneDelegate.invokeTask (eval at 623 (polyfills.js:790), <anonymous>:365:38)
    at Object.onInvokeTask (eval at <anonymous> (vendor.js:602), <anonymous>:44:41)
    at ZoneDelegate.invokeTask (eval at 623 (polyfills.js:790), <anonymous>:364:43)
    at Zone.runTask (eval at 623 (polyfills.js:790), <anonymous>:265:48)
    at drainMicroTaskQueue (eval at 623 (polyfills.js:790), <anonymous>:497:36)
```

When I remove `@import` the Build is OK.

**Comment by steveblue** [comment]
I can't get either .css or .scss files in /src/style to build with the project. Shouldn't webpack be bundling these files as 1 .css file and injecting it in the <head>?

**Comment by Foxandxss** [comment]
It should (for prod, not dev)

**Comment by steveblue** [comment]
Why is the bundling of CSS ignored for dev?

**Comment by Foxandxss** [comment]
No sorry. What is ignored is extracting the CSS outside.

Ps: The gitter is up.

**Comment by ferhtgoldaraz** [comment]
I' m facing a similar issue. It seems that any folder in "src" that is not either "app" or "style" (in my case a "modules" folder) will be parsed by both css or sass loaders.
