### ISSUE TITLE
Getting DEPRECATION WARNING since updating to beta 3

### ISSUE THREAD

**Issue by qdouble** [preboot/angular2-webpack#15]
Since updating to beta 3, I get 

>DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask
lang.ts:356 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
angular2-polyfills.js:1152 DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask

Does the configuration of this seed need to be updated or is it something else?

**Comment by ocombe** [comment]
That doesn't look like things that I use in this starter. I haven't had time to test beta3 yet, I'll check it out this week end.

**Comment by sraparlatmw** [comment]
I am getting the same warning.

**Comment by ocombe** [comment]
It's just because we include the whole angular 2 pollyfill bundle and that it uses deprecated features, nothing to worry about, it will probably be gone with the next release.

**Comment by ocombe** [comment]
We should get less warnings in the next beta :) It's apparently already the case in beta 5 but since it's broken we'll have to wait for beta 6

**Comment by rexebin** [comment]
Beta 6 is now and usable. warnings are still there, guess we need to wait for beta 7.

**Comment by ocombe** [comment]
Yeah, if they don't disappear we will have to cherry pick the polyfills

**Comment by Foxandxss** [comment]
It is not a big deal, it is just a warning. I don't think we should do anything about it.

Let's continue in https://github.com/angular/angular/issues/7007
