### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'import' of undefined

### ISSUE THREAD

**Issue by ayvoia** [preboot/angular2-webpack#150]
hi:
   I use it and code of angular2's official website.
   But it is error.
   Why?
   Error:
      EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'import' of undefined...
      VM7325:84 Error: Uncaught (in promise): TypeError: Cannot read property 'import' of undefined...

   Can you help me?
   Thanks.

**Comment by Foxandxss** [comment]
With that information is completely impossible for me.

**Comment by Zinadore** [comment]
Taking a guess here, but are you trying to use loadChildren to lazy load modules with the new router ? If so i found the solution [here](https://gist.github.com/brandonroberts/02cc07face25886fe142c4dbd8da1340) by Brandon Roberts. If you are using the syntax from the official page, it works only with SystemJS. Webpack needs a custom loader

**Comment by ayvoia** [comment]
This is an example of official,[http://plnkr.co/edit/?p=preview](url)
It uses system.js to be configured,I replaced it with angular2-webpack framework.
And it is error. @Zinadore you are right, I use loadChildren.
Thanks very much @Foxandxss and @Zinadore , I try to use async-ng-module-loader.ts.
Thanks again.
