### ISSUE TITLE
Getting warnings, when running npm run build

### ISSUE THREAD

**Issue by gohilumesh** [preboot/angular2-webpack#153]
Hi All,

When i do "npm run build", I am getting following warning. Can you please let us know how to avoid it. or let me know the fix

Thanks you in advance

WARNING in js/app.bb120f197d4f0d965e5f.js from UglifyJs
Condition always true [./~/angular2-template-loader!./~/@angularclass/hmr-loader!./~/tslint-loader!./src/main.ts:6,4]
Side effects in initialization of unused variable HTMLCollection [./~/@angular/forms/src/directives/select_multiple_control_value_accessor.js:31,0]

WARNING in js/polyfills.bb120f197d4f0d965e5f.js from UglifyJs
Condition always true [./~/angular2-template-loader!./~/@angularclass/hmr-loader!./~/tslint-loader!./src/polyfills.ts:7,4]
Dropping unreachable code [./~/angular2-template-loader!./~/@angularclass/hmr-loader!./~/tslint-loader!./src/polyfills.ts:13,2]
Condition always true [./~/es6-shim/es6-shim.js:15,0]
Dropping unreachable code [./~/es6-shim/es6-shim.js:18,3]
Condition always false [./~/es6-shim/es6-shim.js:95,0]
Dropping unused variable cacheSentinel [./~/reflect-metadata/Reflect.js:809,0]
Condition left of || always false [./~/zone.js/dist/zone.js:623,40]
Condition left of || always false [./~/zone.js/dist/zone.js:624,39]
Dropping side-effect-free statement [./~/zone.js/dist/zone.js:652,0]
Side effects in initialization of unused variable Zone [./~/zone.js/dist/zone.js:152,0]

WARNING in js/vendor.bb120f197d4f0d965e5f.js from UglifyJs
Dropping unused variable __unused [./~/@angular/core/src/di/reflective_injector.js:16,0]
Side effects in initialization of unused variable SecurityContext [./~/@angular/core/src/security.js:26,0]
Side effects in initialization of unused variable ViewType [./~/@angular/core/src/linker/view_type.js:20,0]
Side effects in initialization of unused variable freeExports [./~/rxjs/util/root.js:12,0]
Side effects in initialization of unused variable freeModule [./~/rxjs/util/root.js:13,0]
Dropping unused function normalizeArray [./~/@angular/platform-browser-dynamic/index.js:206,0]
Non-strict equality against boolean: != true [./~/@angular/compiler/src/ml_parser/html_tags.js:40,0]
Side effects in initialization of unused variable TagContentType [./~/@angular/compiler/src/ml_parser/tags.js:14,0]
Side effects in initialization of unused variable strCases [./~/@angular/compiler/src/i18n/serializers/xtb.js:110,0]
Side effects in initialization of unused variable ProviderAstType [./~/@angular/compiler/src/template_parser/template_ast.js:232,0]
Side effects in initialization of unused variable PropertyBindingType [./~/@angular/compiler/src/template_parser/template_ast.js:273,0]
Side effects in initialization of unused variable TypeModifier [./~/@angular/compiler/src/output/output_ast.js:19,0]
Side effects in initialization of unused variable BuiltinMethod [./~/@angular/compiler/src/output/output_ast.js:275,0]
Side effects in initialization of unused variable StmtModifier [./~/@angular/compiler/src/output/output_ast.js:509,0]
Dropping unused function _fetchSylesFromState [./~/@angular/compiler/src/animation/animation_parser.js:115,0]
Dropping unused variable renderMethod [./~/@angular/compiler/src/view_compiler/property_binder.js:68,0]
Side effects in initialization of unused variable transitiveModuleMeta [./~/@angular/compiler/src/runtime_compiler.js:108,0]
Dropping unreachable code [./~/@angular/compiler/src/metadata_resolver.js:340,0]
Declarations in unreachable code! [./~/@angular/compiler/src/metadata_resolver.js:340,0]
Dropping unused variable EVENT [./~/@angular/compiler/src/schema/dom_element_schema_registry.js:19,0]
Dropping unused variable __unused [./~/@angular/common/src/pipes/async_pipe.js:34,0]
Side effects in initialization of unused variable matches [./~/@angular/common/src/facade/intl.js:164,0]
Side effects in initialization of unused variable HTMLCollection [./~/@angular/common/src/forms-deprecated/directives/select_multiple_control_value_accessor.js:31,0]
Dropping unused variable SAFE_SRCSET_PATTERN [./~/@angular/platform-browser/src/security/url_sanitizer.js:39,0]
Side effects in initialization of unused variable RequestMethod [./~/@angular/http/src/enums.js:22,0]
Side effects in initialization of unused variable ReadyState [./~/@angular/http/src/enums.js:37,0]
Side effects in initialization of unused variable ResponseType [./~/@angular/http/src/enums.js:50,0]
Side effects in initialization of unused variable ContentType [./~/@angular/http/src/enums.js:64,0]
Side effects in initialization of unused variable ResponseContentType [./~/@angular/http/src/enums.js:75,0]
Dropping unreachable code [./~/@angular/router/src/apply_redirects.js:72,0]
Declarations in unreachable code! [./~/@angular/router/src/apply_redirects.js:72,0]
Dropping unreachable code [./~/@angular/router/src/apply_redirects.js:96,0]
Declarations in unreachable code! [./~/@angular/router/src/apply_redirects.js:96,0]
Dropping unreachable code [./~/@angular/router/src/create_url_tree.js:160,0]
Declarations in unreachable code! [./~/@angular/router/src/create_url_tree.js:160,0]
Side effects in initialization of unused variable pathLocationStrategy [./~/@angular/router/src/router_module.js:24,0]
Side effects in initialization of unused variable hashLocationStrategy [./~/@angular/router/src/router_module.js:28,0]

**Comment by Foxandxss** [comment]
There is no fix, and there is nothing broken.

Uglify just warns about some stuff, but that is expected.

For example, there is a variable in an if that returns `true` or `false` depending on the environment. For build it will be `true` so it ends like:

`if (true) { ... }` and that is normal, but uglify just warns about that.

So in short, you can ignore those :)
