### ISSUE TITLE
On npm start it throws errors related to scss

### ISSUE THREAD

**Issue by iancian** [preboot/angular2-webpack#155]
![errors and warnings](https://cloud.githubusercontent.com/assets/285696/18007122/01772e08-6ba3-11e6-98b6-0bbecf8eac40.PNG)

Hi,
When I run npm start on my machine I am getting the following errors in screen attached.  I did npm install first.

I am using it with VS Code on Windows 10 and no changes have been done to the code yet.  Am I missing something or do I have something to install first?

Can you assist?
Thanks

**Comment by Foxandxss** [comment]
I heard about this error once but I was never able to reproduce.

Will investigate.

**Comment by iancian** [comment]
Hey guys, 

After sometime playing around, I managed to find the source of the error on Windows 10.
Basically if you are using VS Code, when you right-click, do not use Open in command prompt.  it will give you the error above.

In order to be able to run open the folder through file explorer and open command prompt from there and no issues will rise.

I do not know if this issue is related to any permissions or something of this sort but this worked for me.

**Comment by pjmolina** [comment]
Repro +1 @iancian I can confirm the same issue with VS. The workaround proposed works like charm!
