### ISSUE TITLE
Question: How to define global variables and have individual component SASS files pick them up

### ISSUE THREAD

**Issue by gamemerlin** [preboot/angular2-webpack#156]
I have your starter pack up and running. It is picking up individual sass styles for individual components. But I cannot seem to reference global sass vars defined in my main scss

my entry app.component.ts -> it has main.scss with a global var like $font-color for example

I have a sub component home.component.ts - > with home.scss. It cannot reference $font-color defined in the main.scss

is there a way to do this easily?

**Comment by Foxandxss** [comment]
That is an interesting question. I believe that right now they are completely different.

Sadly my SCSS-fu is really bad, but that is a functionality that I **really** want.

**Comment by mattdistefano** [comment]
Same issue as #126 no?

**Comment by Foxandxss** [comment]
Indeed.
