### ISSUE TITLE
Karma shim zone.js/dist/proxy-zone -> proxy

### ISSUE THREAD

**Issue by tb** [preboot/angular2-webpack#157]
In some of latest zone.js proxy-zone was renamed to proxy.

This results in tests failing with:

    PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
      Error: Cannot find module "zone.js/dist/proxy-zone"
      at webpack:///karma-shim.js:12:0 <- karma-shim.js:58

Fix will probably be:
1) Renaming proxy-zone -> proxy
2) Updating "zone.js": "^0.6.12" to "^0.6.17"

**Comment by Foxandxss** [comment]
Ah yeah, I had to update this in so many places but actually forgot about this one. There were like 2-3 changes in the same day.

**Comment by HexaliteRep** [comment]
@k
