### ISSUE TITLE
IE9: TypeError: Unable to get value of the property 'add': object is null or undefined 

### ISSUE THREAD

**Issue by hijoncon** [preboot/angular2-webpack#158]
Hey guys, anyone encountering this issue in IE9. It happens in binding example. 
`[ngClass]="key: value"`
`[ngModel]="name"`

`TypeError: Unable to get value of the property 'add': object is null or undefined`

**Comment by mattdistefano** [comment]
Troubleshooting some IE9 issues of my own right now so can't confirm but first guess is [classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#Browser_compatibility)

**Comment by hijoncon** [comment]
In gitter they suggested me to use shims_for_IE, I'll try it right now.

**Comment by hijoncon** [comment]
Update: This shims_for_IE works [link](https://github.com/angular/angular/blob/66df335998d097fa8fe46dec41f1183737332021/shims_for_IE.js)
