### ISSUE TITLE
Nothing is being rendered with prod build

### ISSUE THREAD

**Issue by Ibrahim-Islam** [preboot/angular2-webpack#166]
With the prod build, none of my components are being shown. No errors in console and all the relevant apis are being called but no UI rendered. How can debug this situation and I am not good at webpack so how do I turn off inlining of templates in app.js build script?

**Comment by Foxandxss** [comment]
how are you testing your prod build?

**Comment by Ibrahim-Islam** [comment]
I took the contents of the dist folder into my wwwroot folder in Visual Studio running that with IISExpress

**Comment by Foxandxss** [comment]
I suggest you to test it out with say `lite-server` or `http-server` just to discard.

**Comment by Ibrahim-Islam** [comment]
Ok. Will do that. But how do I turn off inlining of templates though?

**Comment by Foxandxss** [comment]
I don't have the answer to that, sorry.
