### ISSUE TITLE
update typings to npm @types

### ISSUE THREAD

**Issue by gxsjtu** [preboot/angular2-webpack#169]
please use npm @types and remove typings

**Comment by Foxandxss** [comment]
There is a PR for that.

**Comment by gxsjtu** [comment]
your mentioned pr is not completed, types section defined in tsconfig is obviously unnecessary as @types decorator is marked under node modules. A more thorough solution is needed.

发自我的 iPhone

在 2016年9月5日，下午4:58，Jesús Rodríguez <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #169<https://github.com/preboot/angular2-webpack/issues/169>.

**Comment by tb** [comment]
AFAIK this will require TypeScript 2, @types/* in package.json and types in tsconfig, see commit https://github.com/AngularClass/angular2-webpack-starter/commit/2f441d924f5fc02f0bff1e40c6ce854ffd83d648

**Comment by Foxandxss** [comment]
That is done already @tb in master.

**Comment by gxsjtu** [comment]
I agree ts2 and nam @types are required, but types in tsconfig is not.
it is totally possible to find typings based on @types decorator.
在 2016年9月5日，下午7:18，Tomasz Bak <notifications@github.com<mailto:notifications@github.com>> 写道：


AFAIK this will require TypeScript 2, @types/* in package.json and types in tsconfig, see commit AngularClass/angular2-webpack-starter@2f441d9<https://github.com/AngularClass/angular2-webpack-starter/commit/2f441d924f5fc02f0bff1e40c6ce854ffd83d648>
