### ISSUE TITLE
importing lodash

### ISSUE THREAD

**Issue by nvitas** [preboot/angular2-webpack#173]
Could you provide an example on importing an external library such as lodash?

I noticed that typings.json file is now gone and I'm getting an error in the console:

./src/app/about/about.component.ts
(2,20): error TS2307: Cannot find module 'lodash'.

But the actual code '_.each(...)' seems to run. 

I installed lodash with npm: 

**'npm i lodash --save'**

and I'm importing it in my component:

**import * as _ from 'lodash';**

I am not including it in the vendor.js file because as the readme states 'import the **css** files in vendor.ts' . I've tried including it there but makes no difference just to make sure.

What's happened to the typings.json file and what should we use instead?

**Comment by mattdistefano** [comment]
Check out https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by nvitas** [comment]
@mattdistefano thanks for that link, makes much more sense now.

i'll try and dig up more info on how it all connects behind the scenes but I have one more question:

when you:
- npm install chart.js is shows up in the package.json as "chart.js": **"2.1.6"** 
-but when you install npm install --save @types/chartjs it is  "@types/chartjs": **"0.0.28"**,

how do you then track the version of the lib you're installing? (This could be a one off for this particular lib and the other libs probably match the latest version when you install with @types/ but this caught my eye and it could get confusing matching versions down the road)
