### ISSUE TITLE
Why "my" ? The selector of your component should have prefix "my"

### ISSUE THREAD

**Issue by samfrach** [preboot/angular2-webpack#174]
Hello,

the coding style says to use a prefix, but this prefix must not be "my".

How can I get rid of this warning ?

thank you

**Comment by Foxandxss** [comment]
Sorry, I need to add proper documentation for this in the README but seems like I never find the time.

in `tslint.json` there is an entry for the prefix. You can either remove it or change the `my` for your own prefix. I highly recommend you on using a prefix, so change it for the one of your choice.

**Comment by samfrach** [comment]
don't be sorry :)

thanks a lot... I was looking for "my".. I don't know how I haven't found it...
