### ISSUE TITLE
Paused on promise rejection: 'Failed to execute 'fetch' on 'Window': 1 argument required, but only 0 present.'

### ISSUE THREAD

**Issue by rubenv** [preboot/angular2-webpack#179]
Starting this package with the Chrome inspector open always causes a breakpoint to be triggered:

![screen shot 2016-09-12 at 09 45 42](https://cloud.githubusercontent.com/assets/42904/18428351/c29a1e10-78cd-11e6-959b-628bd281faac.png)

Angular 2 is completely new to me, so I have no idea where to even start looking for the cause of this.

Doesn't happen on the quickstart example in the Angular docs, so must be related to Webpack (or the configuration here) somehow.

**Comment by onkark** [comment]
I am also getting this error after updating to angular 2.0.0

**Comment by gavinm-ulogic** [comment]
Not a real solution but: changing fetchPromise = global['fetch'](); to fetchPromise = global['fetch'](''); in zone.js fixes the breakpoint problem.

**Comment by JiroDan** [comment]
Seeing the same issue using Systemjs -- no webpack.  Just moved application from rc4 to release.

**Comment by rubenv** [comment]
This is caused by https://github.com/angular/zone.js/issues/446.

Closing this issue.
