### ISSUE TITLE
Routes Not Working on Page Refresh from dist folder

### ISSUE THREAD

**Issue by anishreddy202** [preboot/angular2-webpack#184]

**Comment by Foxandxss** [comment]
how are you running the app from dist folder?

**Comment by anishreddy202** [comment]
Thanks for the quick response, I have executed npm run build and the cd dist and did http-server

Navigations all worked fine for the first time but when i refreshed I get 404 not founds

If I use locationhashstrategy then it works fine but I don't want # in my routes

**Comment by Foxandxss** [comment]
http-server is a bit "meh". Try `lite-server`. Problem is that http-server doesn't support html5mode.

In any case, you need a real server for prod, not http-server nor lite-server.

**Comment by gravity-addiction** [comment]
IIS: I setup a site as normal and point to the base directory. To achieve the dynamic urls I use http://www.iis.net/downloads/microsoft/url-rewrite Web.Config I use looks like

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="AngularJS Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
        <caching enabled="true" enableKernelCache="true">
            <profiles>
                <add extension=".js" policy="DisableCache" kernelCachePolicy="DisableCache" />
            </profiles>
        </caching>
  </system.webServer>
</configuration>
```


Apache: uses the same concept of pointing to a normal website directory. I use the apache mod-rewrite module to achieve dynamic urls using a .htaccess like

```
RewriteEngine on
RewriteBase    /

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule . index.html [NC,L]
```

**Comment by anishreddy202** [comment]
Thank you, ah that makes sense I will be using Nginx to rewrite the urls

**Comment by phra** [comment]
i'm closing this. [related to history fallback on server side, so out of scope of this project]
as @Foxandxss pointed out, just use `lite-server` that has native support to history fallback, i.e. 404s errors are redirected to `index.html`
