### ISSUE TITLE
Keep getting ts experimentalDecorators error

### ISSUE THREAD

**Issue by Ibrahim-Islam** [preboot/angular2-webpack#187]
Before upgrading from es6-shim to core-js and from typings to @types everything was working fine. Also have this error: https://github.com/zloirock/core-js/issues/243

**Comment by Foxandxss** [comment]
Is the error in the console or something you see in your IDE?

**Comment by Ibrahim-Islam** [comment]
I see it in my IDE, VS Code

**Comment by Foxandxss** [comment]
There is an IDE problem with that. TS 2 support is not that good with ides. Do you choose TS2.0.2 when prompted while opening VSCode?

**Comment by Ibrahim-Islam** [comment]
I do not get any prompt to choose TS version. Any idea the problem regarding not being able to recognize `Promise` in ts files?

**Comment by Foxandxss** [comment]
What VSCode are you using? I am at 1.5.2

**Comment by Ibrahim-Islam** [comment]
Thank you for you prompt reply always :)
I had to target the latest typescript to be used in `settings.json` of VS Code http://stackoverflow.com/a/38855826/1565402
