### ISSUE TITLE
@types/protractor no exported member

### ISSUE THREAD

**Issue by hijoncon** [preboot/angular2-webpack#188]
@Foxandxss just fyi: After I did npm install then npm start now getting

`@types/protractor/index.d.ts:22:2
  Module 'webdriver' has no exported member 'IButton'.`

I think this is on the protractor, but not sure...

To reproduce the issue:

1. Remove node_modules
2. npm cache clean
3. npm install
4. npm start

there is at least 33 errors.

**Comment by sparachi** [comment]
I am having similar issue. Eventhough the app works just fine, could someone tell why the issue occurs. i have no knowledge on protractor, and new to angular development.

**Comment by hijoncon** [comment]
This also happen via `npm run build`

**Comment by shijumon** [comment]
Same build error observed via npm run build
attached the screen shot.
![image](https://cloud.githubusercontent.com/assets/7480983/18700600/c835c520-7ff5-11e6-82f7-7750a0561f06.png)

**Comment by TylorShin** [comment]
+1

**Comment by JohanDavidsson** [comment]
Locking the types for selenium webdriver to version 2.44.26 solved the problem for me.

"@types/selenium-webdriver": "^2.44.26" > "@types/selenium-webdriver": "2.44.26",

**Comment by shijumon** [comment]
hi @JohanDavidsson,
        I still see the issue after updating the selenum-webderiver version as you suggested.

**Comment by JohanDavidsson** [comment]
@shijumon Run "npm update" afterwards if you haven't done that. Otherwise it's still the same version as before.

**Comment by shijumon** [comment]
@JohanDavidsson 
I did the following steps,
  1. deleted node_modules folder
  2. npm install 
  
Issue is reproducible while trying to build the project again.
I also tried  npm cache clean.

**Comment by JohanDavidsson** [comment]
@shijumon My project is far from identical with this starter pack by now but I actually did a clean separate install for testing if I had changed something else concerning this. So with the new clean install it didn't work att first but when I applied my change it did work. Sorry but I can´t reproduce your error.

**Comment by ivancduran** [comment]
Same issue here.
Solved locking the types, works for now, thanks @JohanDavidsson

**Comment by shijumon** [comment]
@JohanDavidsson 
I tried a clean install of start pack today. Issue is fixed after applying your suggestion.
But my ongoing project, which is based on starter pack still showing the issue. I will investigate more what else is causing the issue.

**Comment by Foxandxss** [comment]
I locked it for the time being. As soon as I update to protractor 4, it will come with its own typings.

Also I removed the types array at tsconfig, not needed anymore.
