### ISSUE TITLE
AOT NGC Compiler fails on scss @import

### ISSUE THREAD

**Issue by teeSee** [preboot/angular2-webpack#193]
First of all, thank you for this boilerplate!

I am running into a problem on how to use AOT ngc compiler, since I have @import in my component.scss file. Do you know how to resolve this? Getting scss to css instead? Thanks in advance.

**Comment by anasAsh** [comment]
did it work with you?

**Comment by teeSee** [comment]
Oh, I changed the scss to css in component.ts. And it all worked. Thanks for the response.
