### ISSUE TITLE
Migrate to webpack 2

### ISSUE THREAD

**Issue by Foxandxss** [preboot/angular2-webpack#195]
First step to get modern stuff like aot and lazy load

**Comment by nik-lus** [comment]
What do you expect the lazy load to look like w/webpack 2?

With this current (webpack1) seed I'm lazy loading like this:

```
let routes: Routes = [
         { path: 'test', loadChildren: () =>
            new Promise(resolve => {
                (require as any).ensure([], require => {
                    resolve(require('./relativePathTo/Module')['module-name']);
                })
            })
       }
]
```
But this becomes clunky once you start building out multiple routes. There's also [angular2-router-loader](https://www.npmjs.com/package/angular2-router-loader) which abstracts some of that code out but adds more to the tooling chain.

Just wondering if webpack 2 would simplify this process out of the box where we'd be back to what the style guide examples show (currently w/system.js):

```
let routes: Routes = [
     {path: 'test', loadChildren:'./test/test.module#TestModule'},
]
```

**Comment by Foxandxss** [comment]
I will use a new plugin for aot and lazy loading. It has a bug so I will put it ASAP.
