### ISSUE TITLE
Need detailed steps to deploy code in production..

### ISSUE THREAD

**Issue by mmraghavendra** [preboot/angular2-webpack#198]
I am new to angular2 and webpack. code is up and running in dev. But i am not able to understand how to deploy the same code in production after npm run build. I want to deploy it in Heroku. It will be more helpful if you could provide detailed steps on how it could be deployed in production. Thank you..

**Comment by Foxandxss** [comment]
I am not a heroku user, I cannot help you.

But the normal thing is to run `npm run build` and move the `/dist` folder to your server.
