### ISSUE TITLE
Since latest version, direct links don't work anymore

### ISSUE THREAD

**Issue by CSharpFan** [preboot/angular2-webpack#204]
How to reproduce:

````
git clone repo.git my-app
cd my-app
npm install
npm run start:hmr # or npm run start
````

Now navigate to `http://localhost:8080/about`. Doesn't work.

Navigating from `http://localhost:8080/`, and clicking `About` on top does work. 

If we check what gets offered by the webserver, we can clearly see that for `http://localhost:8080/about` there are no scripts.

**Comment by Foxandxss** [comment]
Weird. I will investigate.

**Comment by asktomsk** [comment]
This route should be somewhere in serving (nodejs) code:

```
    // Angular routes support
    app.use("*", function (req, res) {
        res.sendFile(path.join(__dirname, "../public/index.html"));
    });

```

**Comment by Foxandxss** [comment]
The problem is the dev server. I reported it here https://github.com/webpack/webpack-dev-server/issues/640#issuecomment-252321976

**Comment by Foxandxss** [comment]
I reverted to beta 5 which works. As soon as the bug gets fixed, I updated the server again.
