### ISSUE TITLE
Routing doesn't work when we request for a path in the browser address bar

### ISSUE THREAD

**Issue by MehdiSaeedifar** [preboot/angular2-webpack#207]
For example when you enter the address in the browser like **http://localhost:8080/about**, the page freeze on "loading.."..

**Comment by asktomsk** [comment]
1. duplicate
2. it was already fixed in the latest commit

**Comment by MehdiSaeedifar** [comment]
No, it doesn't fixed in the latest commit.

**Comment by MehdiSaeedifar** [comment]
Yeah you are right, it's my fault. this bug origins from **webpack-dev-server 2.1.0-beta.8**

**Comment by Foxandxss** [comment]
In fact comes from beta 6. Team is working on a fix so I will bump to the new version when it comes.
