### ISSUE TITLE
Question. angular2-webpack vs angular2-cli feedback

### ISSUE THREAD

**Issue by jbeckton** [preboot/angular2-webpack#210]
We have been using the Angular CLI for a few months now, We went with that tool because we have some developers that are very new to front end development and wanted to hide all the complexities of the tooling to make things easier. But the CLI has a lot of problems and some of it's dependencies are problematic for our CI pipeline.

I prefer being able to tweak my tooling when needed and the CLI has made that very difficult. So I am trying to build a case for switching from the CLI to the preboot so I was wondering if anyone using this project can share some of their experiences with the CLI vs the preboot.

**Comment by Ibrahim-Islam** [comment]
We initially opted for angular-cli also. But after doing some digging, I suggested we should not go for it. So, out of some Webpack-based starters, I choose this one and went ahead with this for our upgrade from  beta to RC5 and as of now the whole app is in production and based off this starter. It does not have AoT and lazy loading yet but as a basic and minimal starter this is one of the best IMO.

**Comment by Foxandxss** [comment]
Hello!

Thanks for using my starter.

So whether to use CLI or use a starter like this (or any other one) is whether you need access to the tooling or not. The CLI offer a sensible configuration that may work for your project or may not. It is not a silver bullet and it doesn't pretend to be so.

I suggest you to see what would you like the CLI do for you, see if you can achieve that and if not, look for a webpack starter.

---

About AoT and lazy. I am part of the angular 2 docs team and we are working hard pushing AoT to the documentation. The CLI has some cool tooling to to AoT and lazy and I am personally investigating those tools so I can update the angular.io' webpack guide to use webpack 2 + aot + lazy loading.

The idea for the guide is to be as close as possible as the CLI (in terms of folder structure) but without being the CLI.

I will try to map all those knowledge back here to this starter. So soon I will create a branch here where I will put AoT, lazy loading and all the goodies I can.

**Comment by jbeckton** [comment]
As for lazy loading, I was able to get it to work with this project by adding a webpack loader. I have a project at home I am using this starter with and that was one of the first things I noticed was the lazy loading, if I remember correctly it was really simple to add the loader and get it to work.

**Comment by Foxandxss** [comment]
There is an official solution we are brewing and that is what I want to put in here.

**Comment by jbeckton** [comment]
So I was trying out the AngularClass webpack starter and there were some things missing or at least there was not a clear way to accomplish. I think your project is better thought out. One of the things I like about your project is the ability to have style bundles separate from the styles defined inside the angular components js. I have some external libraries that provide our look and feel and I need for them to be applied before Angular finished booting so injecting them into the document head made this possible where as if the styles are bundled into the js files they are not applied until Angular boots up.

Thanks!
