### ISSUE TITLE
npm test gives 'Can't find variable: webpackJsonp' error

### ISSUE THREAD

**Issue by w0bbes** [preboot/angular2-webpack#211]
Hey,

So running 'npm test' gives me a 'Can't find variable: webpackJsonp' error. I did some digging and it has got to do with the CommonsChunkPlugin.

When I remove the following part from the webpack.config.js, 'npm test' will work correctly:
```
new CommonsChunkPlugin({
    name: ['polyfills','vendor']
}),
```

But, when I run 'npm start' and start devving, it will throw random decorator errors (this work fine with the CommonsChunkPlugin active):
```
Uncaught ReferenceError: __decorate is not defined
```

Can anyone tell me how I could fix this?

EDIT:
Small thing I noticed though. When I run 'npm test', it still runs the whole part with the CommonsChunkPlugin, while being inside a '!isTest'.

```
  if (!isTest || !isTestWatch) {

    config.plugins.push(
      new ForkCheckerPlugin(),

      // Generate common chunks if necessary
      // Reference: https://webpack.github.io/docs/code-splitting.html
      // Reference: https://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin
      
      new CommonsChunkPlugin({
        name: ['polyfills','vendor']
      }),
      

      // Inject script and link tags into html files
      // Reference: https://github.com/ampedandwired/html-webpack-plugin
      new HtmlWebpackPlugin({
        template: './src/public/index.html',
        chunksSortMode: 'dependency'
      }),

      // Extract css files
      // Reference: https://github.com/webpack/extract-text-webpack-plugin
      // Disabled when in test mode or not in build mode
      new ExtractTextPlugin({filename: 'css/[name].[hash].css', disable: !isProd})
    );
  }
```

**Comment by Foxandxss** [comment]
Can you try with latest master? For example that first line on your latter snippet changed, that was a bug. it is && and not ||

**Comment by w0bbes** [comment]
Will do and report back today. Thanks

**Comment by w0bbes** [comment]
Fixed it! thanks @Foxandxss !
