### ISSUE TITLE
Can't import .scss in vendor.ts

### ISSUE THREAD

**Issue by khmyznikov** [preboot/angular2-webpack#220]
<img width="566" alt="screen shot 2016-10-21 at 5 09 21 pm" src="https://cloud.githubusercontent.com/assets/6115884/19601259/39ef14aa-97b1-11e6-98b6-a584d01a8959.png">

**Comment by ollwenjones** [comment]
how are you importing it. It looks like you have a bad loader chain - sass to postcss to raw, then sass again?

**Comment by khmyznikov** [comment]
@ollwenjones 
I'm use a default rules from this pack

            `[{
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader?' + atlOptions, 'angular2-template-loader', '@angularclass/hmr-loader'],
                exclude: [isTest ? /\.(e2e)\.ts$/ : /\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/]
            },

            // copy those assets to output
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: 'file?name=fonts/[name].[hash].[ext]?'
            },

            // Support for *.json files.
            {test: /\.json$/, loader: 'json'},

            // Support for CSS as raw text
            // use 'null' loader in test mode (https://github.com/webpack/null-loader)
            // all css in src/style will be bundled in an external css file
            {
                test: /\.css$/,
                exclude: root('src', 'app'),
                loader: isTest ? 'null' : ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: ['css', 'postcss']
                })
            },
            // all css required in src/app files will be merged in js files
            {test: /\.css$/, include: root('src', 'app'), loader: 'raw!postcss'},

            // support for .scss files
            // use 'null' loader in test mode (https://github.com/webpack/null-loader)
            // all css in src/style will be bundled in an external css file
            {
                test: /\.scss$/,
                exclude: root('src', 'app'),
                loader: isTest ? 'null' : ExtractTextPlugin.extract({
                    fallbackLoader: 'style-loader',
                    loader: ['css', 'postcss', 'sass']
                })
            },
            // all css required in src/app files will be merged in js files
            {test: /\.scss$/, exclude: root('src', 'style'), loader: 'raw!postcss!sass'},

            // support for .html as raw text
            // todo: change the loader to something that adds a hash to images
            {test: /\.html$/, loader: 'raw', exclude: root('src', 'public')}
        ]`

**Comment by ollwenjones** [comment]
I mean how are you importing it in vendor.ts?

**Comment by khmyznikov** [comment]
@ollwenjones like another css, but as scss 
`import 'folder-path/file-name.scss';`

**Comment by ollwenjones** [comment]
That's fine. How are you importing it inside vendor.ts?

**Comment by khmyznikov** [comment]
@ollwenjones my vendor.ts file:

```
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';

import 'rxjs';
import '@angularclass/hmr';

// Other vendors for example jQuery, Lodash or Bootstrap
// You can import js, ts, css, sass, ...

import 'bootstrap/dist/css/bootstrap-reboot.min.css';
import 'bootstrap/dist/css/bootstrap-flex.min.css';
import 'bootstrap/scss/_animation.scss';


import 'open-sans-fontface/open-sans.css';

**Comment by ollwenjones** [comment]
that is puzzling. I was expecting to see a `require` with a sass loader chain specified that corresponded to your error. You could try `require(` and see if you get the same result. Any possibility there's actually a syntax error in that file? Otherwise try adjusting the webpack config to make sure it resolves that path to the right loader. Does it produce that error for all `.scss` files, or could it the `_`prefix?

**Comment by strictd** [comment]
try using relative paths for your imports. either import './bootstrap/....'  or import '/bootstrap/...'

```
import './bootstrap/dist/css/bootstrap-reboot.min.css';
import './bootstrap/dist/css/bootstrap-flex.min.css';
import './bootstrap/scss/_animation.scss';


import './open-sans-fontface/open-sans.css';
```

**Comment by khmyznikov** [comment]
@strictd no luck with  './bootstrap/....' or  '/bootstrap - Module not found, it's already relative. Full path - '../node_modules/bootstrap/'.

**Comment by strictd** [comment]
For some reason i missed the very first comment in the thread.. only seen from the second down.. My next thought is that it maybe trying to run both loaders? since you're pulling scss from a directory non-excluded from at least one of the loaders..?

**Comment by khmyznikov** [comment]
@strictd  i guess you are right. I has included some my custom scss and it works. import '../src/style/_common.scss'; Sorry, i'm newbie in webpack, confused a little with loaders.

**Comment by strictd** [comment]
easiest solution is to exclude node_modules from one of the loaders.. exclude accepts either a single path or an array of paths.

```
        // support for .scss files
        // use 'null' loader in test mode (https://github.com/webpack/null-loader)
        // all css in src/style will be bundled in an external css file
        {
            test: /\.scss$/,
            exclude: [root('src', 'app'), root('node_modules')],
            loader: isTest ? 'null' : ExtractTextPlugin.extract({
                fallbackLoader: 'style-loader',
                loader: ['css', 'postcss', 'sass']
            })
        },
        // all css required in src/app files will be merged in js files
        {test: /\.scss$/, exclude: root('src', 'style'), loader: 'raw!postcss!sass'},
```
