### ISSUE TITLE
backend config?

### ISSUE THREAD

**Issue by grauschnabel** [preboot/angular2-webpack#221]
Hi there,

what would be the typical config if I use angular2 as a frontend to a ruby on rails api?

I have a development RoR server and a production RoR server.  How should I wire them up, can I do any config for production and development which can be used in the code?

Thanks,
Martin

**Comment by Foxandxss** [comment]
My recommendation is not to mix your frontend with your backend at all. While you could potentially put this starter (or any other starter) within the /public folder, it is better if you treat both projects as independent projects.

Two different projects and two different repos. For deploy you can decide on CORS or a reverse proxy where all the calls goes to Angular 2 and the /api calls goes to RoR.

**Comment by grauschnabel** [comment]
Maybe I didn't ask right. How can I add different configurations for the server url in the client?

**Comment by Foxandxss** [comment]
Oh, understood you wrong.

This starter doesn't offer anything special for that use case. You can either configure a proxy, use `process.env` to set development urls...

I highly recommend you going to stackoverflow, I am sure there are a lot of patterns for that already, here it is just me.
