### ISSUE TITLE
Include js from node_modules in index.html

### ISSUE THREAD

**Issue by luxsypher** [preboot/angular2-webpack#223]
I'm trying to use ng2-charts with a angular2-webpack project.
ng2-charts requires to include the following line in the index.html

`<script src="/node_modules/chart.js/src/chart.js"></script>`

Ending up with a 
`404: GET http://localhost:8080/node_modules/chart.js/src/chart.js `

What would be the correct path to reach the node_modules folder ?

**Comment by samfrach** [comment]
(I'm not an expert) 

the node_modules folder is not deployed, it used to pack required modules.

my idea would be to place your chart.js in your asset directory....

**Comment by luxsypher** [comment]
Alright found a solution:
All I had to do was 

`npm install chart.js --save`

Then update the vendor.ts by including the Chart.js above the ng2-charts 

```
import 'chart.js/dist/Chart.min.js';
import 'ng2-charts';

```
