### ISSUE TITLE
Sass not supported

### ISSUE THREAD

**Issue by mnn** [preboot/angular2-webpack#224]
Project readme claims support of Sass:

`Stylesheets with SASS (not required, it supports regular css too).`

Yet it doesn't seem to be supported at all:
```
Error in ./src/app/test/test.sass
Module parse failed: /xxx/src/app/test/test.sass Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
*
    color: orange                                                                                                                                           
```

**Comment by Foxandxss** [comment]
I am really ignorant on this CSS pre processors. Isn't 'scss' the same as 'sass'? We are using `.scss` as the extension. But we can activate `.sass` as well.

**Comment by mnn** [comment]
SCSS and SASS format differ (SCSS is a bit enhanced CSS - mainly scoping, SASS goes even further and allows e.g. to omit `{ } ;`).

Googled a bit and fix is suprisingly simple - just modify regexes from `/\.scss$/` to `/\.(scss|sass)$/,`.

**Comment by Foxandxss** [comment]
yup, is pretty much that. Create a PR if you want or I can fix that myself.

**Comment by mnn** [comment]
PR #225 should fix it, closing this issue.
