### ISSUE TITLE
Material2 integration issue

### ISSUE THREAD

**Issue by kuncevic** [preboot/angular2-webpack#226]
It was being a bit of discussion on material2 here https://github.com/preboot/angular2-webpack/pull/201
Currently I am looking how to add material2 to the project.

- `npm install @angular/material --save`
- index.html:

 `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`
- app.module.ts:
```
import { MaterialModule, MdIconRegistry } from '@angular/material';
...
@NgModule({
  imports: [
    BrowserModule,
    HttpModule,
    FormsModule,
    routing,
    MaterialModule
  ],
...
 providers: [
    ApiService,
    MdIconRegistry
  ]
```
- vendors.ts
`import '@angular/material';`  //i think this one just doing nothing

- home.component.html
```
<p>
    <button md-button>FLAT</button>
    <button md-raised-button>RAISED</button>
    <button md-icon-button>
        <md-icon class="md-24">favorite</md-icon>
    </button>
    <button md-fab>
        <md-icon class="md-24">add</md-icon>
    </button>
    <button md-mini-fab>
        <md-icon class="md-24">add</md-icon>
    </button>
</p>
```
That is what I am getting when home page getting loaded:

![image](https://cloud.githubusercontent.com/assets/1283734/19845251/18d2f81a-9f89-11e6-99e8-50f20fe1401c.png)

However it should be looked like this (https://github.com/angular/material2/blob/master/src/lib/button/README.md):

![image](https://cloud.githubusercontent.com/assets/1283734/19845340/1629f1ee-9f8a-11e6-980f-0511fb4a9ddf.png)

Then when I am clicking on rounded `favorite` or `add` buttons I am just getting this (this one is just a side effect I suppose due to missing stylesheets):

![image](https://cloud.githubusercontent.com/assets/1283734/19845282/56c6da9c-9f89-11e6-9703-956b04fb905f.png)

I have such impression that styles didnt load properly.
Any thoughts on this one?

p.s:

Also tried
- vendor.ts
```
import '@angular/material/button/button.css';

import '@angular/material/icon/icon.css';
```

but didn't help

**Comment by Foxandxss** [comment]
Reading material2 github, you need to import a theme.

**Comment by kuncevic** [comment]
@Foxandxss ohh man that was tricky. Just read this https://github.com/angular/material2/blob/master/docs/theming.md

so `import '@angular/material/core/theming/prebuilt/deeppurple-amber.css';` did fix the missing bit.

Thanks a lot.
