### ISSUE TITLE
import log4javascript as 3rd party library

### ISSUE THREAD

**Issue by azulay7** [preboot/angular2-webpack#231]
Hi,
I really like your project, clean and neat.
I'm trying to build a log service of my own that usses 'log4javascript';
I added this library to vendor.ts and to my service.
but when I run it, I get an error:
log4javascript is not defined.

Here is my code:

import { Injectable } from '@angular/core';
import  {Logger} from 'log4javascript';

@Injectable()
export class MyLoggerService {
  log:any;

  constructor() {
    
    this.log=Logger;
    let ajaxAppenderInfo = new log4javascript.AjaxAppender('http://localhost:8989/api/log/info');
    ajaxAppenderInfo.setThreshold(log4javascript.Level.INFO);
    this.log.addAppender(ajaxAppenderInfo);
    this.log.info('Init Info logger');
  }

  info(message){
    this.log.info(message);
  }
}

Thank you in advance :)
Amit

**Comment by Foxandxss** [comment]
You need https://www.npmjs.com/package/@types/log4javascript

**Comment by azulay7** [comment]
I've done it ofcourse. the error is at run time.
when I get to the service Constructor it didn't yet upload 'log4javascript' library.

**Comment by azulay7** [comment]
Ok.. this iw weird I succeed by changing the row from import {Logger} from 'log4javascript';
to 
import * as log from 'log4javascript';

this is suck .

thank you for the answer.

**Comment by Foxandxss** [comment]
The problem is that log4javascript is not ready for ES6 imports (which is what TS uses). That library is like a year and a half old, so the author would need to update it to "modern tools".
