### ISSUE TITLE
[doc] Update readme with global dependencies, if any

### ISSUE THREAD

**Issue by BrainCrumbz** [preboot/angular2-webpack#24]
Hello

thanks for sharing this project. We were looking at a (similar one)[https://github.com/AngularClass/angular2-webpack-starter], and there they mentioned [global dependencies](https://github.com/AngularClass/angular2-webpack-starter#dependencies) to be installed.

Does this starter project need some global dependencies as well? We could not find any mention on readme about it.

Thanks

**Comment by Foxandxss** [comment]
The only one really needed is typescript (which is mentioned in the README).

The others (webpack, the server, typings, karma...) are installed as a devDependencies. That way you don't force the user to have them globally installed and better than that, you ensure that your project always have the latest versions (who don't forget to update global libraries time to time?).

**Comment by BrainCrumbz** [comment]
Thanks for quick feedback. Regards!

**Comment by Foxandxss** [comment]
Any time. If you see something and you think it is wrong, don't mind opening an issue.

**Comment by ocombe** [comment]
Actually you need to install typescript globally either, it's a dev dependency of the starter and you never have to call "tsc" manually.
We should remove this line from the readme.

**Comment by Foxandxss** [comment]
Indeed, figured it out later that it is just for `tsc`.
