### ISSUE TITLE
npm run build fails with Node v6.5.0

### ISSUE THREAD

**Issue by mbpolan** [preboot/angular2-webpack#242]
Hey everyone,

I'm trying to build an app by invoking "npm run build" using NodeJS v6.5.0 and NPM 3.10.3 on CentOS 7. I already ran "npm install" prior which finished without any complaints. I saw some similar issues with Node v6.x like #93 and #97, and an almost exact one [here](https://github.com/KadoTomohiro/angular2-minimum/issues/1), but nothing has helped.

Here's the output I see:

`Version: webpack 2.1.0-beta.26
Time: 809ms
    + 3 hidden modules

ERROR in ./src/polyfills.ts
Module build failed: TypeError: Can't add property fileName, object is not extensible
    at Object.Linter (/home/jenkins/workspace/my-app/node_modules/tslint/lib/tslint.js:12:23)

ERROR in ./src/vendor.ts
Module build failed: TypeError: Can't add property fileName, object is not extensible
    at Object.Linter (/home/jenkins/workspace/my-app/node_modules/tslint/lib/tslint.js:12:23)

ERROR in ./src/main.ts
Module build failed: TypeError: Can't add property fileName, object is not extensible
    at Object.Linter (/home/jenkins/workspace/my-app/node_modules/tslint/lib/tslint.js:12:23)
Child html-webpack-plugin for "index.html":
        + 4 hidden modules

npm ERR! Linux 3.10.0-327.18.2.el7.x86_64
npm ERR! argv "/opt/nodejs/node-v6.5.0-linux-x64/bin/node" "/opt/nodejs/node-v6.5.0-linux-x64/bin/npm" "run" "build"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! my-app@1.0.0 build: `rimraf dist && webpack --progress --profile --bail`
npm ERR! Exit status 2`

Any ideas? Thanks!

**Comment by Foxandxss** [comment]
Check the latest commit, there is a fix for beta.26

**Comment by mbpolan** [comment]
Thanks! The new code fixed the problem.

**Comment by PraveenGottala1** [comment]
can you please elaborate on this issue?

**Comment by Foxandxss** [comment]
Breaking change on webpack, but that is fixed in the starter, just needed to add the `-loader` part to every loader in use.
