### ISSUE TITLE
Unable to load css from node_modules

### ISSUE THREAD

**Issue by MadhuJutur** [preboot/angular2-webpack#246]
Hi Team, 
I am facing issue loading CSS files from node_modules. Please help, this issue is bothering me a lot :(

**Comment by Foxandxss** [comment]
If you don't give me any more information, I don't know what you are doing.

**Comment by MadhuJutur** [comment]
@Foxandxss, Thank you for quick replay. 

I have installed primeNG 
_npm install primeng --save_
Installation is all good. 

Now when I am trying to include CSS references like below in my index.html under 'public' folder

_<link rel="stylesheet" type="text/css" href="/node_modules/primeng/resources/themes/omega/theme.css" />
<link rel="stylesheet" type="text/css" href="/node_modules/primeng/resources/primeng.min.css" />_

I am getting an issue loading styles
![image](https://cloud.githubusercontent.com/assets/5411731/20349975/c722023e-ac32-11e6-991d-1c4f62daa1c3.png)

**Comment by Foxandxss** [comment]
Don't do that. Go to your `app.scss` and do:

```
@import "~primeng/resources/themes/omega/theme.css"
@import "~primeng/resources/primeng.min.css"
```

**Comment by MadhuJutur** [comment]
Hi @Foxandxss, 
Initially tried with above suggestion and I got below issue

![image](https://cloud.githubusercontent.com/assets/5411731/20350304/635514ce-ac34-11e6-8c02-509cc2525c27.png)

**Comment by Foxandxss** [comment]
you need semicolons at the end of each import, forgot to tell you that.

**Comment by syeddk** [comment]
After adding the semicolons, its throwing below error

![image](https://cloud.githubusercontent.com/assets/11690208/20351013/23408186-ac37-11e6-9ccc-c0d8db1d536c.png)

**Comment by Foxandxss** [comment]
Ugh, you got me there. I will need to try myself that library.

**Comment by Foxandxss** [comment]
Try something else. Instead of doing it on the `app.css`, go to `vendor.ts` and try:

```
import 'node_modules/primeng/resources/themes/omega/theme.css';
import 'node_modules/primeng/resources/primeng.min.css';
```

**Comment by syeddk** [comment]
Sorry to bother you @Foxandxss I have tried this approach earlier and came across issue ie 
`Error: Cannot find module "node_modules/primeng/resources/primeng.min.css"`

**Comment by Foxandxss** [comment]
Oh, it was without "node_modules/"

**Comment by syeddk** [comment]
Issue just rolled back to, after making suggested changes.
`Error: Cannot find module "./images/loading.gif"`

If you don't mind, It would be great if you can try install primeNG and include CSS references.
Actually I have been trying various options to resolve the issue, but hard luck

**Comment by Foxandxss** [comment]
I tried. That `loading.gif` is not related to primeng so your error is somewhere else.

**Comment by MadhuJutur** [comment]
Thank you @Foxandxss, Actually I have cloned latest copy from git and worked on top of it and it works like charm :)

**Comment by germansokolov13** [comment]
For those who stumble here. You can add these lines to `app.scss` to add PrimeNG styles to your app. For importing css-files and not scss-files in Sass it's essential to omit `.css` or they will compile into dynamic import instead of being inlined by Sass.
```
@import "~primeng/resources/themes/omega/theme.scss";
@import "~primeng/resources/primeng";
```
