### ISSUE TITLE
Using Ionicons with this seed

### ISSUE THREAD

**Issue by stefanstelzer** [preboot/angular2-webpack#253]
Hey folks, 

Can you help me implementing Ionicons into the seed?

**Comment by mattdistefano** [comment]
See https://github.com/preboot/angular2-webpack#how-to-include-external-css-files-such-as-bootstrapcss- + you may need to adjust the font path in the ionicon css.

**Comment by stefanstelzer** [comment]
Hey @mattdistefano ,

don´t think that this is the solution! Manipulating a dependency source will never be a good idea. Just think about updating. Solved it by adjusting the assets output.

`// copy those assets to output
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader?publicPath=../&name=./fonts/[name].[hash].[ext]?'
      },`
