### ISSUE TITLE
webpack@2.0.7-beta does not satisfy its siblings' peerDependencies requirements

### ISSUE THREAD

**Issue by BrainCrumbz** [preboot/angular2-webpack#26]
Trying to `npm install` on a freshly downloaded copy, we get:

~~~
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.0.7-beta does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer extract-text-webpack-plugin@1.0.1 wants webpack@^1.9.11
npm ERR! peerinvalid Peer sass-loader@3.1.2 wants webpack@^1.12.6
npm ERR! peerinvalid Peer istanbul-instrumenter-loader@0.1.3 wants webpack@1.x.x
npm ERR! peerinvalid Peer karma-webpack@1.7.0 wants webpack@^1.4.0
npm ERR! peerinvalid Peer webpack-dev-server@2.0.0-beta wants webpack@>=2.0.3-beta <3

npm ERR! Please include the following file with any support request:
npm ERR!     D:\<some path>\angular2-webpack\npm-debug.log
~~~

Current environment is:

* Windows 10 x64
* NVM 1.1.0
* node 4.3.0
* npm 2.14.12
* tsc 1.0.3.0

No global package installed beside npm and typescript

**Comment by Foxandxss** [comment]
The problem with webpack 2 right now is that it is a beta and some loaders are locked to 1.x so you get a lot of warning of that kind.

If you check, extract-text-plugin wants 1.x but still works with webpack 2. Same with the others.

If you do a `npm start`, does it work?

**Comment by BrainCrumbz** [comment]
I see. It seems not. 

Maybe we should wait for a more stable webpack version and that all used plugins catch up with that. ... Having Angular 2 in beta is enough! :smile: 

~~~
npm start

> app@0.0.0 start D:\<some-path>\angular2-webpack
> npm run server


> app@0.0.0 server D:\<some-path>\angular2-webpack
> webpack-dev-server --env dev --inline --progress --port 3000

Config did not export an object.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 server: `webpack-dev-server --env dev --inline --progress --port 3000`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the app@0.0.0 server script 'webpack-dev-server --env dev --inline --progress --port 3000'.
npm ERR! This is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --env dev --inline --progress --port 3000
npm ERR! You can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\<some-path>\angular2-webpack\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 start: `npm run server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.0 start script 'npm run server'.
npm ERR! This is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server
npm ERR! You can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\<some-path>\angular2-webpack\npm-debug.log
~~~

**Comment by ocombe** [comment]
> Config did not export an object.
Did you change the webpack.config.js file ?

**Comment by ocombe** [comment]
Also the reason why we use webpack 2 is that it includes environment variables that helps a lot for builds, and we should be able to do tree shaking (reduce the size of the builded files by removing unused modules) soon.

**Comment by Foxandxss** [comment]
All the siblings issues will go away eventually, the starter works fine as is (if you don't mind the warnings).

Still, check your config.

**Comment by BrainCrumbz** [comment]
Code base is untouched. Just downloaded and extracted zip. Please find a pastebin [here](http://pastebin.com/5TjC2tUm)

**Comment by BrainCrumbz** [comment]
BTW thanks guys for you quick support. If this takes too much, we might as well check it again in the future.

**Comment by ocombe** [comment]
That weird then, I've installed it from fresh on windows yesterday on 2 different computers (windows 10 x64) and it worked fine.
The difference is that I was using node 5 & npm 3...

**Comment by BrainCrumbz** [comment]
We might try switching node.js version at least, and see what happens.

**Comment by BrainCrumbz** [comment]
With node 5.6.0 and npm 3.6.0, `npm install` works fine, as well as `npm start` and `npm run test`. Not sure you want to mention this potential issue in readme or what.

Thank you both

**Comment by ocombe** [comment]
Thanks for testing this. We will have to update the readme. I wonder if the problem is with node or npm 3.
