### ISSUE TITLE
npm install fails with missing peer dep for webpack

### ISSUE THREAD

**Issue by ekarlso** [preboot/angular2-webpack#27]
│ ├─┬ http-proxy-middleware@0.9.1 
│ │ └─┬ micromatch@2.3.7 
│ │   ├─┬ arr-diff@2.0.0 
│ │   │ └── arr-flatten@1.0.1 
│ │   ├─┬ braces@1.8.3 
│ │   │ ├─┬ expand-range@1.8.1 
│ │   │ │ └─┬ fill-range@2.2.3 
│ │   │ │   ├── is-number@2.1.0 
│ │   │ │   ├── isobject@2.0.0 
│ │   │ │   └── randomatic@1.1.5 
│ │   │ ├── preserve@0.2.0 
│ │   │ └── repeat-element@1.1.2 
│ │   ├── expand-brackets@0.1.4 
│ │   ├── extglob@0.3.2 
│ │   ├── filename-regex@2.0.0 
│ │   ├─┬ kind-of@3.0.2 
│ │   │ └── is-buffer@1.1.2 
│ │   ├── normalize-path@2.0.1 
│ │   ├─┬ object.omit@2.0.0 
│ │   │ ├─┬ for-own@0.1.3 
│ │   │ │ └── for-in@0.1.4 
│ │   │ └── is-extendable@0.1.1 
│ │   ├─┬ parse-glob@3.0.4 
│ │   │ ├── glob-base@0.3.0 
│ │   │ └── is-dotfile@1.0.2 
│ │   └─┬ regex-cache@0.4.2 
│ │     ├── is-equal-shallow@0.1.3 
│ │     └── is-primitive@2.0.0 
│ ├── open@0.0.5 
│ ├─┬ serve-index@1.7.3 
│ │ └─┬ accepts@1.2.13 
│ │   └── negotiator@0.5.3 
│ ├─┬ sockjs@0.3.15 
│ │ └─┬ faye-websocket@0.9.4 
│ │   └─┬ websocket-driver@0.6.4 
│ │     └── websocket-extensions@0.1.1 
│ ├─┬ sockjs-client@1.0.3 
│ │ ├─┬ eventsource@0.1.6 
│ │ │ └── original@1.0.0 
│ │ ├── faye-websocket@0.7.3 
│ │ ├── json3@3.3.2 
│ │ └─┬ url-parse@1.0.5 
│ │   └── querystringify@0.0.3 
│ ├── stream-cache@0.0.2 
│ ├── strip-ansi@3.0.0 
│ ├── supports-color@3.1.2 
│ ├── UNMET PEER DEPENDENCY webpack@>=1.0.0 <3
│ └─┬ yargs@3.32.0 
│   ├── camelcase@2.1.0 
│   ├── cliui@3.1.0 
│   └── window-size@0.1.4 

It's blowing up on npm install :(

**Comment by Foxandxss** [comment]
Shouldn't blow it. But give me 10 hours (AKA when I wake up tomorrow) that I am gonna revert to webpack 1.x so it is the best solution for now.

We will update to webpack 2.x when it gets more stable.

**Comment by ekarlso** [comment]
: o, thanks man!

2016-02-16 0:35 GMT+01:00 Jesús Rodríguez <notifications@github.com>:
