### ISSUE TITLE
Is this starter enough for me?

### ISSUE THREAD

**Issue by PiotrKalinski** [preboot/angular2-webpack#271]
Hello, 

I am starting my first commercial project, not so super big enterprise application but with like 10 modules with some visualization, D3JS and few other things. Is this starter enough for me to make, test and deploy?  I have found angular2 webpack starter from AngularClass but it seems too much for me and I won't handle everything what is there.

**Comment by Foxandxss** [comment]
That for granted.

The good part is that normally if you decide to migrate tomorrow, you only need to move the src app.

**Comment by PiotrKalinski** [comment]
Thanks for fast response, I will love to use that and improve my programming skills!
