### ISSUE TITLE
Error: Cannot match any routes. URL Segment: 'dist'

### ISSUE THREAD

**Issue by rishparekh** [preboot/angular2-webpack#278]
I have generated production build and copied 'dist' folder to tomcat. and whenever i am launching the app
using http://localhost:8080/dist/, i am getting below error 
EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'dist'
Error: Cannot match any routes. URL Segment: 'dist'

I have checked  routing but there is no route specified by the name 'dist'
Starting route name is 'login'.
is it because the folder name is dist, its looking for route having name 'dist' ?
Please help.

**Comment by Foxandxss** [comment]
you need to move the **content** of `dist` not the whole folder. On the other hand, to fix your actual problem, you would need to change the base href in the index.html to contain the /dist/

**Comment by rishparekh** [comment]
@Foxandxss Thanks a lot .. cheers
changed base href and its working
