### ISSUE TITLE
Cannot find name 'Partial'

### ISSUE THREAD

**Issue by shaikhspear16** [preboot/angular2-webpack#280]
error in latest repo!!!

```
[at-loader] node_modules\@types\lodash\index.d.ts:245:25 
    Cannot find name 'Partial'.
```

**Comment by Foxandxss** [comment]
Did you update the tsconfig Just to rule stuff out.

**Comment by moonflare** [comment]
@shaikhspear16 It looks like the issue is caused by the `Typescript` version. Try to update it to `2.1` [Read more](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14311#issuecomment-275834057)

**Comment by shaikhspear16** [comment]
Updating to 2.1 fixed. Thanks.
