### ISSUE TITLE
140 issues on fresh clone

### ISSUE THREAD

**Issue by mcescalante** [preboot/angular2-webpack#283]
On a fresh clone and `npm install` I am seeing the following output after `npm start`

`[at-loader] Checking finished with 140 errors`

All of the errors are apparently `@types/lodash`. I have another previously cloned copy of this project with changes working fine without these errors. Screenshot of part of the console below:

![screenshot](https://i.imgur.com/BJZoNnQ.png)

What could be going wrong? Do I have the wrong version of something globally?

**Comment by Foxandxss** [comment]
No, you are not. Count to 5 and fresh clone again.

**Comment by mcescalante** [comment]
Okay, I just re-cloned and am seeing the same issue. Is there a reason you believe I'm not seeing these errors?

**Comment by Foxandxss** [comment]
you didn't count to 5!

Try again. There was some params on tsconfig that are quite aggresive.

**Comment by mcescalante** [comment]
@Foxandxss I was confused for a second! lol.

Sadly, the config updates doesn't seem to have gotten rid of the errors for me. It's almost like I have wrong versions of something installed globally

**Comment by Foxandxss** [comment]
for the sake of trying, could you bump typescript to 2.1.5?

**Comment by mcescalante** [comment]
Thank you for your speedy responses. Seems to have fixed it!

```
[at-loader] Checking started in a separate process...
[at-loader] Ok, 2.01 sec.
```
![screenshot](https://i.imgur.com/RFGrU87.png)

Will bumping this to 2.1.x cause any other issues? I saw in another issue that you said there are some incompatibilities between Angular and 2.1.x

**Comment by Foxandxss** [comment]
Yes, AOT + TS2.1 is a no-no.

I just created a conversation around this issue at the angular slack.

**Comment by mcescalante** [comment]
Okay, cool. So should I not proceed with 2.1.5 and wait? Ignore those errors? I can't seem to find a previous commit that works on a fresh clone (even though my previous project is OK), and I'm confused about what is throwing those errors

**Comment by mcescalante** [comment]
@Foxandxss this appears to be a regression introduced upstream: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13994

More discussion in another issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14338

Running the command `npm install @types/lodash@4.14.50` immediately fixed all issues for me with a fresh clone of this project (using Typescript 2.0.10)

As someone else pointed out, it's a bummer that a small patch level semver issue causes this issue and requires TS 2.1 or to manually roll back to 4.14.50.

Maybe for now, it's worth locking `@types/lodash@4.14.50` in package.json

**Comment by GaryB432** [comment]
Did removing the `tsconfig` options help?  A shame that we can't use those to prohibit unused names. The console screen shot above seems to point to the lodash typings being too new (the 'no-no' 2.1) which I believe is a different issue than the compiler options.

**Comment by mcescalante** [comment]
No @GaryB432 `tsconfig` wasn't the issue here. It is `@types/lodash@4.14.51` causing the issue.

If you do a fresh clone, you have to manually roll back to `@types/lodash@4.14.50` to get the errors to stop.

**Comment by GaryB432** [comment]
I just really like those compiler options and if they stay removed from `master` here, even though not causing a problem, I'll just have to maintain my own branch which is a minor inconvenience that I have not had to take yet.

**Comment by Foxandxss** [comment]
Yeah, I did wrong. Open a PR and rererevert it. Too many things erroring today

**Comment by mcescalante** [comment]
Just went ahead and added the tsconfig changes back into the PR I just opened. This PR also locks the @types/lodash version properly to avoid any errors. I will keep a close eye here and submit any additional PRs needed as changes happen upstream :)
