### ISSUE TITLE
Interest in using ava?

### ISSUE THREAD

**Issue by chrisjlee** [preboot/angular2-webpack#285]
Is there any interest from other folks to use [ava](https://github.com/avajs/ava)?

**Comment by Foxandxss** [comment]
Sounds good, but I better go with what Angular supports officially.

**Comment by ollwenjones** [comment]
@chrisjlee if you have something working I would be interested in seeing a gist, etc. The typical Angular test stack has been kind of a pain point for me (config headaches, false positives, odd failures, slowness, etc.) I didn't realize how bad it really was until I stepped into the React space and saw what the alternatives were. I understand Jesus' reason for going with "the standard" esp. for a seed project like this, but I think testing alternatives is an overlooked area of investigation in the Angular community in general.

**Comment by Foxandxss** [comment]
Definitely interesting to see, I guess that the different hacks we have for testing, works on this ava too. I used to love test'em btw.

**Comment by chrisjlee** [comment]
@Foxandxss Would love to see that some experimentation with that. The slowness is a pain point. 

@all I'll try to get something up here. Thanks for your input everybody.

**Comment by ollwenjones** [comment]
FWIW I have enjoyed using Jest in the React space (which shares some similar ideas to AVA)... Very little setup, you provide it a typescript parser, so it doesn't have to be piped through compile steps, etc. Other things they do would be more controversial in the Angular space such as _not testing in a browser at all_, snapshot testing. I think "shallow rendering" for unit tests is a big win though.
