### ISSUE TITLE
Packages/Lines to remove dev-server

### ISSUE THREAD

**Issue by yeralin** [preboot/angular2-webpack#293]
Hi,

I have a question. What npm packages/lines do I need to remove in order to get rid of this webpack-dev server?

For ex., I definitely need to remove this webpack-dev-server and html-loader. What else?

I'm using Django as my backend, and I don't need this dev server at all.

Thank you :)

**Comment by Foxandxss** [comment]
The fact that you are using django as a backend has nothing to do with the frontend server.

Just don't mix your backend and frontend. They are two separated applications and they should remain the same.

That is my advice.

You don't need to remove anything, just don't execute the "npm start" and you will be fine

**Comment by yeralin** [comment]
I just don't want to have excessive packages. I'm using built-in Django dev server :)

**Comment by Foxandxss** [comment]
Well, there is one for each on the package.json, you can remove then, but again, bad idea on mixing your apps.
