### ISSUE TITLE
Project won't build correctly

### ISSUE THREAD

**Issue by yeralin** [preboot/angular2-webpack#297]
$ npm run build
fails with:

```
[at-loader] Checking finished with 3 errors
Error in bail mode: [at-loader] node_modules/@types/jasmine/index.d.ts:39:52
    TS1005: '=' expected.

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 build: `rimraf dist && webpack --progress --profile --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.0 build script 'rimraf dist && webpack --progress --profile --bail'.
```

**Comment by Foxandxss** [comment]
I fixed that issue yesterday. You need to lock down the jasmine typings.

**Comment by mcescalante** [comment]
@Foxandxss I don't see a commit in master that locks down `@types/jasmine` - I was just going to submit a PR for this very thing. Am I looking in the wrong place? :)

**Comment by Foxandxss** [comment]
Uh, weird. I thought I did. Or was that a dream?

Nonetheless, please do @mcescalante

**Comment by yeralin** [comment]
So, should I wait for @mcescalante or lock typings for Jasmine?

**Comment by Foxandxss** [comment]
You can do it locally, will be the same.

**Comment by mcescalante** [comment]
You can do either @yeralin - I will have the PR in the next 5 minutes.

If you want to lock it in yourself:
```
"devDependencies": {
  "@types/jasmine": "2.5.41"
}
```

**Comment by amacoder** [comment]
Upgrading typescript to 2.1.6 solved the problem:
http://stackoverflow.com/questions/42317687/node-modules-types-jasmine-index-d-ts-error-ts1005-expected

**Comment by Foxandxss** [comment]
I don't know how many times I had to say this already. Angular v2 doesn't work with Typescript 2.1.x
