### ISSUE TITLE
When are you gonna switch to Webpack 2?

### ISSUE THREAD

**Issue by yeralin** [preboot/angular2-webpack#300]
When are you gonna switch to Webpack 2?

**Comment by JunkyDeLuxe** [comment]
It's already Webpack2, look package.json deps'
"webpack": "2.1.0-beta.25"

2017-02-16 4:51 GMT+01:00 Daniyar Yeralin <notifications@github.com>:

**Comment by mcescalante** [comment]
If you're getting the version number from something like `webpack -h` it could be a globally installed webpack from npm and you can update it with `npm update -g webpack`. Having a global install of webpack is actually not recommended: https://webpack.js.org/guides/installation/#global-installation
