### ISSUE TITLE
Is't support AOT and server side rendering?

### ISSUE THREAD

**Issue by biapar** [preboot/angular2-webpack#313]
Is't support AOT and server side rendering?

**Comment by Foxandxss** [comment]
Not for now. AOT I want to support it this month, since I need it for other projects. I need to research more for server side rendering.

**Comment by olingerc** [comment]
Would you have an update on this?

**Comment by Foxandxss** [comment]
Yes. Let the ng-conf pass and I start working on this. We are working on the new Angular site and that consumes all my time now.

**Comment by mamoot64** [comment]
Yop,

AoT is now supported ? It's a very important feature.

**Comment by Foxandxss** [comment]
No, it is not. Probably won't. I am not working on this repo anymore. CLI does everything that this does and way more.
