### ISSUE TITLE
why awesome-typescript-loader over ts-loader

### ISSUE THREAD

**Issue by BrkCoder** [preboot/angular2-webpack#320]
Why do you prefer awesome-typescript-loader over ts-loader?

**Comment by ollwenjones** [comment]
This had mostly to do with performance, as I recall. Folks were seeing significant slowdown after certain releases of tsloader. It might play better with the hmr setup as well, but I'm not certain.

**Comment by Foxandxss** [comment]
Sorry, I don't have an answer. I had a reason back in the day but I forgot.

I remember that ts-loader wasn't moving forward as fast or had less features. Probably the inclusion of a loader or other changed forced my hand in here.
