### ISSUE TITLE
templateUrl instead of template

### ISSUE THREAD

**Issue by ekarlso** [preboot/angular2-webpack#37]
Is there a way to use templateUrl instead of template with require?

**Comment by ocombe** [comment]
Hello,

no, not that I know.

**Comment by ekarlso** [comment]
Why not ? Is it best practice to use require or ?

**Comment by Foxandxss** [comment]
What do you want to achieve with that anyway? At the end you want your templates inside the bundle so it doesn't really matter at the end.

**Comment by ekarlso** [comment]
Fair enough, case settled :)


2016-02-22 23:29 GMT+01:00 Jesús Rodríguez <notifications@github.com>:

**Comment by Foxandxss** [comment]
Don't get me wrong mate, I love to discuss stuff. Perhaps I am missing some point so I am open to understand your point of view for the case we can do better :)
