### ISSUE TITLE
Missing shims for IE

### ISSUE THREAD

**Issue by crbranch** [preboot/angular2-webpack#44]
Angular2 beta 7 currently requires several shims to work with IE.  If you build and run the project as-is in IE11, it will throw several exceptions and fail to start:

    Line: 38
    Error: Object doesn't support property or method 'keys'
    Line: 422
    Error: Unable to get property 'createFromList' of undefined or null reference

To fix, I modified vendor.ts to add the following lines at the top:

    // fixes for IE
    import 'es6-shim/es6-shim.js';
    import './shims_for_IE.js';

The `shims_for_IE.js` file is located in node_modules/angular2/es6/dev/src/testing/shims_for_IE.js.  However, I was not able to `import` directly from this path.  Webpack kept claiming that it could not find the file/directory.  I'm not sure if a package.json file somewhere along the path is confusing things, or  why that doesn't work.  I finally gave up and copied `shims_for_IE.js` to the `my-app\src` folder so that it sits next to `vendor.ts`.

**Comment by ocombe** [comment]
Thanks, I added the missing shims.
You were right that it doesn't import from `node_modules/angular2/es6/dev/src/testing/shims_for_IE.js`, but I don't know why though...
@Foxandxss any idea ?

**Comment by Foxandxss** [comment]
I have no idea.

**Comment by ericmartinezr** [comment]
@ocombe @Foxandxss according to the finding of the user in this issue https://github.com/angular/angular/issues/7259 the problem is because of `exclude : ["node_modules"]` in tsconfig.json as you have here https://github.com/preboot/angular2-webpack/blob/master/tsconfig.json#L11

**Comment by Foxandxss** [comment]
That is pretty much what I thought (I tried without it, but takes waaaaay longer and lot of errors). I got confused because you can do `import 'angular2/bundles/angular-polyfills.js` and not that one.

So I thought about all of them on node_modules are UMD bundles so it works and the ignore is not applied for them.

Too much coincidences I thought.

So yeah, I don't think removing that is an option.
