### ISSUE TITLE
test-watch fails

### ISSUE THREAD

**Issue by cmelion** [preboot/angular2-webpack#45]
Indeed, no permutation of 'karma start' works for me unless the npm task is named 'test'.

output from npm run test-watch:
/Users/cfulneck/.nvm/versions/node/v5.6.0/bin/node /Users/cfulneck/.nvm/versions/node/v5.6.0/bin/npm run-script test-watch

> app@0.0.0 test-watch /software/cmelion/angular2-webpack
> karma start --no-single-run --auto-watch

ts-loader: Using typescript@1.8.2 and /software/cmelion/angular2-webpack/tsconfig.json

WARNING in ./src/app/app.spec.ts
[4, 3]: unused variable: 'injectAsync'
[6, 3]: unused variable: 'TestComponentBuilder'
[10, 35]: unused variable: 'Response'
[10, 45]: unused variable: 'ResponseOptions'
[34, 47]: missing whitespace

WARNING in ./src/app/app.spec.ts
Module parse failed: /software/cmelion/angular2-webpack/node_modules/tslint-loader/index.js!/software/cmelion/angular2-webpack/src/app/app.spec.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import {
|   it,
|   inject,
 @ ./src \.spec\.ts

.
.
.
webpack: bundle is now VALID.
28 02 2016 14:29:07.654:WARN [karma]: No captured browser, open http://localhost:9876/
28 02 2016 14:29:07.661:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
28 02 2016 14:29:07.664:INFO [launcher]: Starting browser PhantomJS2
28 02 2016 14:29:08.286:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#o1RrFo5G96eL_HVhAAAA with id 58356197
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: webpackJsonp
  at /software/cmelion/angular2-webpack/karma-shim.js:1

**Comment by Foxandxss** [comment]
Haven't tried yet but what you says makes sense.

We use npm script names to condition the webpack and I forgot about test-watch, no support for that one. Will fix soon.

**Comment by cmelion** [comment]
@Foxandxss yes, that was it.
https://github.com/preboot/angular2-webpack/commit/a4ffd825c45ab6a68f6aa7ca4765a5857fe869be
