### ISSUE TITLE
How to add vendor SVG TTF etc.

### ISSUE THREAD

**Issue by Enlitened** [preboot/angular2-webpack#53]
Do you know how it would be possible to include files like SVG and TTF in the build? When I add the imports into vendor.ts, I get the following error:

`Failed to decode downloaded font: http://localhost:3000/`

`OTS parsing error: invalid version tag`

Any ideas?

**Comment by gravity-addiction** [comment]
your config loader pry isn't catching the file extensions. what does your config test: regex look like?

**Comment by Enlitened** [comment]
I haven't actually changed anything in the config, just using the default angular2-webpack one.

**Comment by kuncevich** [comment]
Any updated on this one? I just fall to similar issue using `material-design-lite` https://github.com/preboot/angular2-webpack/issues/59

**Comment by Foxandxss** [comment]
You won't find one from me sadly. I have no idea on fonts. The config we added in here is just the default one you would add in any project that should technically work.

@ocombe any idea?
