### ISSUE TITLE
[Question] jQuery inclusion for Bootstrap

### ISSUE THREAD

**Issue by vdeturckheim** [preboot/angular2-webpack#54]
Hi,

First of all, thanks a lot for this great starter. It is probably the best and simplest I have found around.
I have an issue in making the `jQuery` variable global in order to use bootstrap's js.
In my vendor.ts, I have: 
```js
// Other vendors for example jQuery, Lodash or Bootstrap
// You can import js, ts, css, sass, ...
import 'jquery/dist/jquery.js'
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/js/bootstrap.js';
```
I tried using `require` on jQuery but it always gave me the same error: 
```
Uncaught Error: Bootstrap's JavaScript requires jQuery
```
Can anyone let me know how to do ? 
Thanks a lot !

**Comment by tb** [comment]
Add to webpack config:

    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jquery: "jQuery",
            "windows.jQuery": "jquery"
        }),
    ]

**Comment by vdeturckheim** [comment]
Thanks a lot !
