### ISSUE TITLE
[question] How do I import alertify.js

### ISSUE THREAD

**Issue by milkisevil** [preboot/angular2-webpack#56]
I'm a webpack n00b and trying to figure out how to use this starter with [alertify.js](https://github.com/alertifyjs).

I'm confused as there has previously been an [alertify issue discussed before](https://github.com/alertifyjs/alertify.js/issues/62) so not sure whether my problem relates to that or my use of angular2-webpack. 

`npm install alertify.js --save`

about.ts
```
import {Component, OnInit} from 'angular2/core';
import alertify from 'alertify.js';

@Component({
  selector: 'about',
  template: require('./about.html'),
  styles: [require('./about.scss')],
  providers: [],
  directives: [],
  pipes: []
})
export class About implements OnInit {

  constructor() {
    // Do stuff
  }

  ngOnInit() {
    console.log('Hello About');
    alertify.success("Alertify is working!");
  }

}
```

JS Console
```
./src/app/components/about/about.ts
(2,22): error TS2307: Cannot find module 'alertify.js'.
```

Any help appreciated!

**Comment by ocombe** [comment]
Hello, since they don't export ES6 modules but node modules, you will need to do `var alertify = require('alertify.js');`

**Comment by milkisevil** [comment]
@ocombe Thanks for the super quick reply, and solution!

**Comment by DRakeshKumar** [comment]
Hello, I am trying to implement alertify.js in my angular 4 app,its already implemented but i can't change the position of the alertify.js...it is always coming in bottom-left part..anyano knos how can i fix the position to top-right?any help would be highly appreciated....thanks

**Comment by Foxandxss** [comment]
That doesn't belong here @DRakeshKumar. Ask on their repo.

**Comment by taiwoobe** [comment]
You can use .logPosition('bottom right').
Example:
alertify.logPosition('bottom right').delay(3000).maxLogItems(3).success('Fixer confirmed successfully!');

**Comment by ichucolon** [comment]
Hi, I am installing alertify.js in vs code, I am getting these errors:

npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

There is no node_module folder created. Anyone, please help me.

**Comment by BasuraRatnayake-zz** [comment]
I found the following method work.
npm install alertify.js@^1.0.12 --save

import * as alertify from 'alertify.js';

alertify.logPosition('bottom right').success(`Messahe`);

**Comment by simnovus** [comment]
First you need to install it with 

`npm install alertifyjs --save`

Next you have to import the following in the angular.json file
> "node_modules/alertifyjs/build/alertify.min.js" in the scripts array 
and 
> "node_modules/alertifyjs/build/css/alertify.min.css",
> "node_modules/alertifyjs/build/css/themes/default.min.css",
in the styles array

You also need to import the alertifyjs in the componentyou have to use it. 

Write `import * as alertify from 'alertifyjs';` at the top of the component to import it in your component.
Now its ready for use.

for eg:
`alertify.minimalDialog || alertify.dialog('minimalDialog',function(){
      return {
          main:function(content){
              this.setContent(content); 
          }
      };
    });
    alertify.minimalDialog("Minimal button-less dialog.");`

**Comment by anothershubham** [comment]
First you need to install it with
`npm install alertifyjs --save`

Next you have to import the following in the angular.json file

> "node_modules/alertifyjs/build/alertify.min.js" in the scripts array and 

> "node_modules/alertifyjs/build/css/alertify.min.css" and 

> "node_modules/alertifyjs/build/css/themes/default.min.css" in the styles array

You also need to import the alertifyjs in the component you have to use it.
Write `import * as alertify from 'alertifyjs';` at the top of the component to import it in your component.
for eg:
`alertify.minimalDialog || alertify.dialog('minimalDialog',function(){ return { main:function(content){ this.setContent(content); } }; }); alertify.minimalDialog("Minimal button-less dialog.");`
