### ISSUE TITLE
'isTest = true' freezing the build process

### ISSUE THREAD

**Issue by kuncevich** [preboot/angular2-webpack#58]
I just set `isTest = true;` in `webpack.config.js` build just freezes at `404s will fallback to /index.html`
```
d:\Projects\angular2-webpack>npm start

> app@0.0.0 start d:\Projects\angular2-webpack
> npm run server


> app@0.0.0 server d:\Projects\angular2-webpack
> webpack-dev-server --inline --progress --port 8080


webpack: bundle is now VALID.
http://localhost:8080/
webpack result is served from /
content is served from ./src/public
404s will fallback to /index.html
```
Sound like an issue. Also FYI in that case I was referencing the latest angular2 beta.12

**Comment by Foxandxss** [comment]
And why you do that? That will disable a lot of webpack features (hence your 404s).

The idea is to disable those features on testing so the test goes faster, but you don't want that for development nor production.

**Comment by kuncevich** [comment]
@Foxandxss I was looking for a way keep all `css/js` files separate so I can visually check the javascript file in a browser individually so was checking if `isTest = true` can help.

Currently I have my files looking like that:
```
<script src="/js/common.js"></script><script src="/js/vendor.js"></script><script src="/js/app.js"></script></body>
```
And if I open lets say `/js/app.js` it is actually `webpackJsonp` with lots of stuff injected by webpack

**Comment by Foxandxss** [comment]
The code that split the css and the js is ExtractTextPlugin that we do only for production in here (in test there is no css at all). You may want to remove the condition in there of "just production to not for test".

Having all your final bundles decorated with Webpack stuff is normal.

**Comment by kuncevich** [comment]
Bu looking in to config it is seams like `ExtractTextPlugin` manipulating with styles(css/scss) not with js:
```
{
        test: /\.css$/,
        exclude: root('src', 'app'),
        loader: isTest ? 'null' : ExtractTextPlugin.extract('style', 'css?sourceMap!postcss')
      },
```
```
 {
        test: /\.scss$/,
        exclude: root('src', 'app'),
        loader: isTest ? 'null' : ExtractTextPlugin.extract('style', 'css?sourceMap!postcss!sass')
      },
```
So what would be is the best way to keep `css/js` separate for debugging purposes?

**Comment by Foxandxss** [comment]
I just told you. ExtractTextPlugin.

**Comment by Foxandxss** [comment]
In Webpack, all the CSS is bundled with the Javascript, but using ExtractTextPlugin, you can separate all the CSS (or a different thing) into a different file. Look line 212.
