### ISSUE TITLE
Problem importing material design lite and route changing

### ISSUE THREAD

**Issue by jedmundo** [preboot/angular2-webpack#72]
I used the guidelines to import third-party css libraries to import material design lite:

In vendor.ts:
// Material Design Lite
import 'material-design-lite/dist/material.indigo-blue.min.css';
import 'material-design-lite/dist/material.min.js';

There is a strange problem happening, when I change route within the angular2 app it looks like all the styles from material design are lost.

I added material design through npm with:
npm install --save material-design-lite

This behaviour is also the same when I compile and run the production build. (npm run build)

**Comment by Foxandxss** [comment]
That is weird. I will debug it later.

**Comment by jedmundo** [comment]
Were you able to reproduce the issue?

**Comment by Foxandxss** [comment]
Sorry, haven't tried yet, too much things to think at once.

**Comment by jedmundo** [comment]
Ok sorry. Because this is really a critical issue for me

**Comment by Foxandxss** [comment]
Sorry my friend, I just maintain lot of projects and I was yesterday all day AFK. I will try to do it later after I finish this work assignment.

**Comment by jedmundo** [comment]
No problem I totally understand.
This is a big issue for me because I get this problem also in production otherwise I wouldn't be bothered.

PS: I miss clicked the close button.

**Comment by Foxandxss** [comment]
I cloned the repo, installed the package, added the two imports. Added some fab buttons and a card at home route. I go to about, I go back to home and it is still there.

What should I do to reproduce it?

**Comment by jedmundo** [comment]
Could you please send me the code you tested with? Ill check it ou.

**Comment by jedmundo** [comment]
I just did that:

1. Cloned the repo
2. Ran npm install
3. Ran npm install material-design-lite --save
4. Added these lines to vendor.ts:

- import 'material-design-lite/material.css'
- import 'material-design-lite/material.min.js'

5. Added 1 button to Home and About:

<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
  <i class="material-icons">CLICK HOME</i>
</button>

6. When you change routes you can see the ripple effect from clicking the button isn't there anymore

**Comment by Foxandxss** [comment]
Ah, completely forgot about this, so sorry. Will try again with your proposed steps.

**Comment by jedmundo** [comment]
Any progress ?

**Comment by Foxandxss** [comment]
It is a legit bug, I don't think it is related with my starter. It is material design lite or router issue. I will dig more.

**Comment by Foxandxss** [comment]
Well, MDL guys sent me to Stackoverflow so I recommend you asking on SO then.

Sorry, that is all the help I can offer you.

**Comment by Foxandxss** [comment]
Oh, the problem is actually documented here: https://getmdl.io/started/#dynamic

**Comment by jedmundo** [comment]
OK thank you and sorry for the trouble!

**Comment by jedmundo** [comment]
Its strange that in the example from john papa: http://a2-first-look.azurewebsites.net/examples/storyline-tracker/plnkr.demo.html?bust=1461665077305

It uses MDL and that doesnt happen..

**Comment by asadsahi** [comment]
for RC4 this works form:

```
 ngAfterViewInit() {
    componentHandler.upgradeDom();
  }
```

I have to call on every component where I am using mdl, but there could be smarter way to achieve this, on every route change success perhaps.

**Comment by ollwenjones** [comment]
Using MDL component JS inside an angular 2 context seems like an anti-pattern to me, akin to using jQuery to manipulate the DOM inside angular context. Using the CSS shouldn't be a problem, but things like the ripple effect (which are accomplished via JavaScript) would have problems, it seems to me mainly because MDL won't know when Angular 2 has manipulated the DOM, will it?

**Comment by ollwenjones** [comment]
MDL JS is really intended for use within otherwise static web-pages.

**Comment by asadsahi** [comment]
Sounds reasonable @ollwenjones . Hence ng2Material :)

**Comment by ollwenjones** [comment]
@asadsahi I actually started off using MDL CSS and building angular 2 components around it, until I found out about ng2-material. Only reason I know anything about it.
