### ISSUE TITLE
Json file 404

### ISSUE THREAD

**Issue by kuncevich** [preboot/angular2-webpack#74]
I just placed `json` file under `services/api` but when running the app my json file is not available and server returning `404` status. 

`404` - `Cannot GET /services/api/data.json`

**Comment by ocombe** [comment]
And when you try to access it manually it works ?

**Comment by kuncevich** [comment]
@ocombe yeah just even run npm run build` the file is not there. I there is a some sort `json` configurations in current `webpack.config.js` what are they actually for?
```
/**
   * Resolve
   * Reference: http://webpack.github.io/docs/configuration.html#resolve
   */
config.resolve = {
    cache: !isTest,
    root: root(),
    // only discover files that have those extensions
    extensions: ['', '.ts', '.js', '.json', '.css', '.scss', '.html'],
    alias: {
      'app': 'src/app',
      'common': 'src/common'
    }
  };
```

```
 // Support for *.json files.
      {test: /\.json$/, loader: 'json'},
```

**Comment by kuncevich** [comment]
OK the thing is I just copy my file in to `public` folder and it is gets copied over automatically with this thing: 
```
// Copy assets from the public folder
      // Reference: https://github.com/kevlened/copy-webpack-plugin
      new CopyWebpackPlugin([{
        from: root('src/public')
      }])
```
