### ISSUE TITLE
Unknown typings dependency es6-shim

### ISSUE THREAD

**Issue by sdornan** [preboot/angular2-webpack#75]
I am trying to update my project based off your template with the change you make as you make them.

With the most recent changes, I am running `npm install` and getting:
```
typings ERR! message Unknown dependency: registry:dt/es6-shim#0.31.2+20160317120654

typings ERR! cwd /Users/sam/Code/groupinn
typings ERR! system Darwin 15.4.0
typings ERR! command "/usr/local/Cellar/node/5.10.1/bin/node" "/Users/sam/Code/groupinn/node_modules/typings/dist/bin/typings-install.js"
typings ERR! node -v v5.10.1
typings ERR! typings -v 0.6.10

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```

Not sure why it's an unknown dependency, since I can do `npm install es6-shim --ambient --save` and it adds the exact same version number to `typings.json`.

**Comment by Foxandxss** [comment]
My bad, I put that typings with a modern installation and this project had an old typings.
