### ISSUE TITLE
Only works when deployed to root of host

### ISSUE THREAD

**Issue by GaryB432** [preboot/angular2-webpack#81]
I copied the dist contents to `mydomain.com/path/to/myapp` and found the scripts and other webpacked stuff was 404ing looking for `mydomain.com/js/vendor.[hash].js` (etc).  I see that your `publicPath` (line 60 in webpack.config.js) is set to '/'. I changed it to *empty string* and it seems to work.

But I see that line is involved in your recent font work.  I'm not using fonts for the time being, so, as I mentioned, my site seems to be working in a subfolder but I didn't want to vary substantially from your awesome config and spoil my option for fonts later. 

I wondered if anyone else found a way to run in a production subfolder. Is that intentionally not supported?  Is that in general a bad practice?

**Comment by gravity-addiction** [comment]
I change this line in webpack.config.js
```
publicPath: isProd ? '/' : 'http://localhost:8080/',

to

publicPath: isProd ? '/my-sub/' : 'http://localhost:8080/my-sub/',
```

**Comment by GaryB432** [comment]
Keeping my site up-to-date with this repo has been as simple as replacing this src with my own. After I make this suggested change, essentially forking the critical piece, e.g., webpack.config.js, that will be a little more difficult.  Nothing I can't handle though!

**Comment by Foxandxss** [comment]
Yeah, one starter alone can't cover all use cases. The normal thing to do is to grab the one you like and modify it as needed.
