### ISSUE TITLE
Is this starter ready for RC0?

### ISSUE THREAD

**Issue by jimbojetlag** [preboot/angular2-webpack#82]
Any known issues if used for an RC0 project?

**Comment by Foxandxss** [comment]
As soon I catch my breath I will update it

**Comment by jimbojetlag** [comment]
Wow, that was quicker than IRC.

**Comment by jimbojetlag** [comment]
@Foxandxss don't bother with RC0, RC1 is out.

**Comment by Foxandxss** [comment]
No worries my friend, I work for Angular so I see them coming :P

**Comment by kuncevic** [comment]
@jimbojetlag how you getting so recent updates ? I can see it was just released exactly 2 hours back https://github.com/angular/angular/releases/tag/2.0.0-rc.1 exactly in time when you commented about it.

**Comment by jimbojetlag** [comment]
@kuncevic in 2016, javascript packages are released before your ice cream is melted. https://gitter.im/angular/angular

**Comment by Foxandxss** [comment]
Now it is ready for business.

**Comment by jimbojetlag** [comment]
👍
