### ISSUE TITLE
what prompted the new layouts?

### ISSUE THREAD

**Issue by gravity-addiction** [preboot/angular2-webpack#86]
I'm having some issues understanding the new layouts.. so are we just putting all directives, pipes, services, components into one folder? is the .component.ts something that is required? seems to me like it's going to be difficult for anyone with a project larger than a couple of pages to find anything they need.

With this new structure, i'd have 37 folders in my app/ directory and have no idea what was a component/pipe/directive/service without going into the folder and see what the file extensions are. I don't get this new layout.

**Comment by Foxandxss** [comment]
This is to follow the new style guide https://angular.io/style guide.  Feel free to change it for your project.

**Comment by Foxandxss** [comment]
I'll be iterating for a while (because we are iterating with the guide too). Feel free to delete the app folder and start over.

**Comment by gravity-addiction** [comment]
it just sucks, the directory structure sucks for large projects, pulling updates from your repo is now near impossible. /rant

For me this structure only works in a fully spec'd app environment. Any sort of continuous development project will turn into a mess of spaghetti. I believe this because there are multiple places in this structure to put the exact same functionality.

**Comment by Foxandxss** [comment]
An starter project is a project you clone once and adapt to your needs. After that, you can cherry pick the commits you like to update yours.

If you don't like the structure, that is fine, you can delete it and start over, the webpack configuration is the exact same one.

**Comment by ollwenjones** [comment]
@gravity-addiction, the `angular.io/style` link didn't work for me, but browsing here at master, it actually seems to follow what has been a recommendation for a while, where all the files _related to a feature_ are together, regardless of type. It turns out to be a lot more maintainable for really large projects than organization by type, where the you can find everything of a given type easily, but you have to navigate the code-base to see what features depend on it. It's worth wrapping your head around.

Also what @Foxandxss just said regarding starter projects.
>
If you don't like the structure, that is fine, you can delete it and start over, the webpack configuration is the exact same one.
>

There's huge value in that.

**Comment by ollwenjones** [comment]
another helpful recommendation from JohnPapa was that if the _name_ of the thing doesn't make it immediately clear what type of thing it is, append the type, e.g. `unclear_name.service.ts` is clearly a service, even if it's name doesn't scream "service."

**Comment by gravity-addiction** [comment]
For me, I don't like to duplicate code. For instance creating a directive to set focus.. I create this directive in a project.. Later on I need to use the set focus directive for another feature.. Do I copy/paste the directive into the new feature? refactor the set-focus to a shared folder? Once its in the shared folder, how do I know to grab it as a dependency when i copy the entire feature to another project? 

I put all my service files into a service folder.. I don't need to have insanely long file names because I don't put my service files in with my component files. Say I need to do a simple personnel lookup, in the accepted directory structure, I should/would need to copy the entire personnel feature over to do one simple task.

Please help me wrap my head around this. i've been developing for over 20 years and never seen something as messy as this structure is going to get.

**Comment by Foxandxss** [comment]
Let's divide this in two things:

First, if you don't like what the angular's style guide suggest, you can open an issue [here](https://github.com/angular/angular.io/issues). I am not trying to impose anything, I just work there so I try to make this starter as close as possible.

Perhaps with that you can see what is the real value on the structure or convince the people to change it, but that is really outside this starter.

Second, if you don't really like the folder structure, you can simply do `rm -rf src/app` and start over in the way you want. The structure here is just a suggestion and the tooling itself is pretty much agnostic.

---

That being said. If a directive is used within a feature, put it on a shared folder of the feature, if it is used between features, the "global" shared features. If you really really want to use that directive in a different project, please don't copy & paste it, create a npm package.

**Comment by gravity-addiction** [comment]
@Foxandxss how about you tell me how i can delete your app folder a 5th time? you've said it 4 times in this thread.. the same sort of stupidity is what created this convoluted folder structure.

**Comment by ollwenjones** [comment]
geez :trollface:

**Comment by Foxandxss** [comment]
I have been treating you in a good manner. I hear your complains, but I cannot please everyone's needs. This starter is mine and it has **my** opinions. The idea is that people that has the same opinions use it and who don't, just look for alternatives. There are lots of different starters out there, and if you don't put any effort, you can make your own.
