### ISSUE TITLE
Old router

### ISSUE THREAD

**Issue by kuncevic** [preboot/angular2-webpack#87]
I can see the old router being used.
`import { ROUTER_PROVIDERS } from '@angular/router-deprecated';`

Is there any issues with a new one?

**Comment by Foxandxss** [comment]
As soon as we put documentation for it, I switch it here

**Comment by kuncevic** [comment]
There is a two sources on the new router https://coryrylan.com/blog/introduction-to-angular-2-routing and this one https://github.com/DanWahlin/Angular2-JumpStart which is already implementing that.

**Comment by Foxandxss** [comment]
Yupp. I work for the Angular 2 team & style guide so I am updating this starter as soon as we make some new decisions and release new doc. New router needs work yet so I am not recommending it yet.

**Comment by yaroslavya** [comment]
@Foxandxss Is it still the case? Seems like the new router is quite stable already. Does it make sense to close this one? :8ball:

**Comment by Foxandxss** [comment]
Indeed, I changed this long ago.
