### ISSUE TITLE
close the thread, i'm not done.

### ISSUE THREAD

**Issue by gravity-addiction** [preboot/angular2-webpack#89]
you totally changed your folder structure mid-project. it's not like this style standard is new, it's been out for months.. i've lost all respect for your projects continuity. No way anyone in their right mind should follow this project after these recent changes.

**Comment by Foxandxss** [comment]
Good to hear.

**Comment by Foxandxss** [comment]
For what is worth. A starter is just a set of **opinions**, each person has its own opinion and heck, each person has its own starter even. I express here my **opinions** and my opinions only. All the people who agrees with me can use the project and those people that doesn't, can use a different starter.

I still want to know what kind of "big" problem this new changes caused to you. You don't like the app structure, that is fine, that is the first thing that goes away when someone creates a new project. I am not forcing you to go to your applications and change the entire structure to the new one, I only changed **my** starter, you are free to continue developing your apps using your own conventions and cherry picking all the changes I put in here if you like them.

I am sorry mate, but you cannot please everybody at once, but thankfully all the configuration is visible and can be changed without any hassle.

**Comment by gravity-addiction** [comment]
my "big" problem is change where change wasn't required. a lot of people
followed you because of your opinion, now you've changed that opinion. It
wasn't like this folder standard was just released, or was designed for any
release candidate reason. In the case you wanted to use the style guide
format, why not from the beginning? at this point I feel that you're going
to take this seed in whatever direction suits *You* best. Sure i'll cherry
pick your root folder updates like I do anyone else. I can no longer, with
good conscious, direct anyone to your project as a starter, and the few
that I have will now need an explanation to why the starter I've
recommended changed so much.

**Comment by SomeKittens** [comment]
> at this point I feel that you're going to take this seed in whatever direction suits *You* best.

...Yes, he is.  He's going to take _his_ project and do what he wants with it.  That's how projects work.  He's not beholden to you in any way.

**Comment by wesleycho** [comment]
The style guide was only finalized recently.

In any case, the reaction to this change is disproportionate to the change itself - I'd recommend stepping back from the computer and calming down, it reflects extremely poorly & is completely unproductive.

**Comment by gravity-addiction** [comment]
@Randall_Koutnik you'd make a great politician. He's not beholden to me at
all, not ever mentioned, he doesn't even have to acknowledge me, yet he
does so i continue to give my point of view. As harshly as it maybe taken,
to me the people listening at just soft.
@Wesley_Cho no one cares about your morals or beliefs, especially not me.

**Comment by SomeKittens** [comment]
If you're not paying for it, he's not obligated to do anything for you.

**Comment by TheLarkInn** [comment]
@gravity-addiction have you considered forking a previous commit of the repository so you can further develop that version?

**Comment by TheLarkInn** [comment]
There are some other light angular2-webpack repo's that encourage forking and breaking out so that it works for your own stack. 

https://github.com/TheLarkInn/angular2-webpack-lite

Also if you are wanting to learn more about webpack, you can check out their documentation or catch some slides I prepared covering the basics so you have the confidence to build your own sauce. 

https://docs.google.com/presentation/d/10mIapWjv1pyUQaMv6G8MCdoe9OK2Ey8zz-CLkHuFdRI/edit?usp=sharing

**Comment by gravity-addiction** [comment]
@Randall_Koutnik He's not even obligated to listen to my opinion, yet he
chooses to by acknowledging with a response. Not sure I can make my point
of view on this any more clear. Maybe you're suggesting that people
shouldn't have opinions to public projects? It's not nice to tell people
their wrong, working at making the internet a safe space are you?

**Comment by gravity-addiction** [comment]
@Sean_Larkin Thank You.

**Comment by trollboy** [comment]
Yeah, I'm with TheLarkinn, show us how it's done. Make your own bootstrap with ngBlackjack & ngHookers and show us how it's done.  Until then, we're all at the mercy of the whims of the person who actually owns the project.

**Comment by gravity-addiction** [comment]
@Matt_Wiseman I Agree! sometimes if you want it done right you gotta do it
yourself. coupled with put your money with your mouth is. I'm on it.

**Comment by trollboy** [comment]
I look forward to seeing it gravity-addiction!  Lemme know when you start your project so I can follow it. I also recommend keeping following this one as well.  Perhaps you two can get code and ideas from each other, maybe in the future the two code bases will become as such where they can be merged and be a more awesome thing than the sum of it's parts.  That's sort of what happened with pigdin im, they ported for encryption as two separate projects for a LONG time, and have since re-merged.    So to you gravity, I quote the great Cromulon race when I say "Show us what you got".

**Comment by SomeKittens** [comment]
Oh, and make sure that you never make any changes whatsoever to your project, as someone might be depending on the old version.  Then you might have to deal with angry, entitled script kiddies banging on about how terrible everything you've done is.

That sounds terrible.

**Comment by wesleycho** [comment]
The point is to frame the opinions in a constructive way - throwing insults and incoherent attacks does not get any closer to a solution to the claimed problem. It is unprofessional, and has no place in open source, and most importantly, doesn't help you and only wastes everyone's energy unnecessarily, which holds back open source as a whole.

If there is a fundamental disagreement, that is ok - in open source, it is as easy as creating a separate project/fork and doing it your own way.
