### ISSUE TITLE
How would you debug in vscode?

### ISSUE THREAD

**Issue by kuncevic** [preboot/angular2-webpack#92]
Just wondering what is the best approach to debug using vscode?

Should I just run `npm run build` https://github.com/preboot/angular2-webpack/issues/93  and debug `dist` by running `live-server` or something or there is a better way?

**Comment by Foxandxss** [comment]
What you mean with debug in here? Because `build` will create your production build and with debug I think about development.

**Comment by kuncevic** [comment]
Ah OK my bad so how would you debug anyway.

**Comment by Foxandxss** [comment]
Wrong person to ask, I survive with console.logs and that is definitely not the way to go :/

Better if you ask in SO or other sites, because I cannot be of any help.

**Comment by kuncevic** [comment]
Get bored by `console.log`..
Was trying to use this thing https://github.com/Microsoft/vscode-chrome-debug but no look I think because of webpack. Haven't dig much in to that after all.
Then looked in to this one http://schempy.com/2016/01/19/angular2_webpack_typescript/ but not working for me when trying to set breakpoints in chrome as mentioned in article.

**Comment by Foxandxss** [comment]
Will take a peek at both and if I get something interesting, I could update the README here.

**Comment by kuncevic** [comment]
Cool. Checkout my update above.
