### ISSUE TITLE
'npm run build' ERROR in chunk vendor when using node 6.x

### ISSUE THREAD

**Issue by kuncevic** [preboot/angular2-webpack#93]
getting error when running `npm run build`

```
ERROR in chunk vendor [initial]
js/[name].[hash].js
No template for dependency: TemplateArgumentDependency
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

**Comment by Foxandxss** [comment]
Uh, weird. I will try with a fresh build.

**Comment by Foxandxss** [comment]
What node & npm are you using? Works for me.

**Comment by kuncevic** [comment]
`Node 6.1` `NPM 3.8.6`  I will check with node 5 and 4 now.

**Comment by kuncevic** [comment]
So I just double check with a fresh project and yes there is an exact issue I described above when using `node 6.1`

`Node 5.8` and `npm 3.8.5` - OK
`Node 4.4.0` and `npm 3.8.2` - OK

Also FYI I am on Win 10.

**Comment by Foxandxss** [comment]
I heard that node 6.x is giving issues, but I will check.

**Comment by ncrawlins** [comment]
this happened for me, because I changed the nodevars.bat to load node and start in "c:/work".

If I changed that to to "C:/work" it builds fine.  Apparently node 6 is treating C:\foo and c:\foo as different places or something. so you have to be careful if you're ever explicitly using windows drive letter somewhere

https://github.com/nodejs/node/issues/6624

**Comment by matsprea** [comment]
I had this issue with `Node 6.1`, but the upgrade to `Node 6.2.1` solved it.
Hope this helps.

**Comment by alexbet** [comment]
I have Node 6.4.0 and have this issue. Was anyone able to resolve it?

**Comment by michaeljota** [comment]
I'm using this proyect, but I'm getting this same issue. How do you guys solve it?

**Comment by kuncevic** [comment]
@michaeljota just do not use `node 6.1` use https://github.com/creationix/nvm to switch to another verson.
