### ISSUE TITLE
404 in readme

### ISSUE THREAD

**Issue by GaryB432** [preboot/angular2-webpack#95]
The relative link to the Style Guide is broken `angular.io/styleguide`

**Comment by Foxandxss** [comment]
Oh snap. Want to create a PR? (I can fix that myself too).

**Comment by GaryB432** [comment]
I would but I'm at the office (not supposed to be looking at this stuff! haha)

**Comment by Foxandxss** [comment]
But... it is good stuff!

Will fix it 👍 

thanks for the report.

**Comment by Foxandxss** [comment]
Done.
