### ISSUE TITLE
`npm run build` error

### ISSUE THREAD

**Issue by tech-no-logical** [preboot/angular2-webpack#97]
from a clean clone, running this gets me 

    > app@0.0.0 build /foo/angular2-webpack
    > rimraf dist && webpack --progress --profile --bail

    /foo/angular2-webpack/webpack.config.js:212
          new CopyWebpackPlugin([{
          ^

    TypeError: CopyWebpackPlugin is not a function

the webpack config looks good to me, but I've got like zero experience with it, so I'm kind of lost :)

**Comment by kuncevic** [comment]
have you run `npm install` first?

**Comment by tech-no-logical** [comment]
yup. npm start works, npm run watch works, but this one doesn't

**Comment by tech-no-logical** [comment]
replacing

    new CopyWebpackPlugin(...) 
with

    new CopyWebpackPlugin.default(...)
fixes it for me. looks like a problem with the plugin ?

**Comment by Foxandxss** [comment]
Will check later to see if there is a new version of something and broke this up

**Comment by kuncevic** [comment]
`npm run build` working for me
I am on `Win10`, `npm  3.8.5` `node 5.8.0`

**Comment by tech-no-logical** [comment]
not on ububtu xenial with npm 3.5.2 and node 4.2.6. weird.

**Comment by kuncevic** [comment]
try to latest `4.x` or latest `5.x` node verston  but not `6.x` due to this one https://github.com/preboot/angular2-webpack/issues/93

**Comment by ndeitch** [comment]
Hey guys,

When I run: `npm run build` after `npm install` I get some errors of TypeScript as: 
```
ERROR in ./src/polyfills.ts
(15,3): error TS2304: Cannot find name 'require'.
 ```
And no ``dist`` folder is created.

My node version and npm version is:

```
node -v
v5.0.0

npm -v
3.3.6
```

Any thoughts?

Thx

**Comment by Foxandxss** [comment]
do you have a typings folder?

**Comment by ndeitch** [comment]
No, Should I? I only have a typings.json

**Comment by Foxandxss** [comment]
Yes, and for some reason it is not doing it for you. Perhaps because you have an old npm (you should install a later version, they are faster).

You can generate the folder if you do

$ ./node_modules/.bin/typings install

But again, should do it for you.

**Comment by ndeitch** [comment]
I exec the command U said and now it's working, the folder dist was created as expected.

I guess that this problem is because I'm running node commands as sudo, I'll fix it and update npm.

Thx for the support!

**Comment by rajegit** [comment]
I have run this code, it build the dist folder and eveything works fine. but there is nothing on browser when i open index.html . It shows loading , nothing on console as well ...

**Comment by rajegit** [comment]
answered by @Foxandxss 
You need a server to serve the page. Try lite-server or http-server

$ npm install -g  #lite-server
$ lite-server

That inside the dist folder.
SOLVE #120

**Comment by phra** [comment]
i'm closing this.
