### ISSUE TITLE
npm bootstrap scss

### ISSUE THREAD

**Issue by hijoncon** [preboot/angular2-webpack#99]
Hi Guys,

How to include `@import '../../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss';` in your `app/styles.scss`?

Getting this error messages:
`ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader!./src/style/app.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/bootstrap/glyphicons-halflings-regular.eot in /Users/x203949/Sites/ng2_retirement/src/style
 @ ./~/css-loader?sourceMap!./~/postcss-loader!./~/sass-loader!./src/style/app.scss 6:4172-4234 6:4257-4319`

**Comment by tb** [comment]
Add:

    $icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
    @import '~bootstrap-sass/assets/stylesheets/_bootstrap.scss';

**Comment by hijoncon** [comment]
thanks tb! :)
